// The fictional sample catalogue from the Claude Design handoff (MODEL-150).
// ALL DATA IS FICTIONAL: every model, lab, benchmark and provider name is made
// up. Ported faithfully from docs/design/handoff/core-flow/modelspec-data.js;
// src/decide/__tests__/parity.test.ts compares this port with that file.
import type {
  BenchDef,
  Catalogue,
  Evidence,
  Facet,
  HostDef,
  LabDef,
  Model,
  Offering,
  RawModel,
  Template,
  TypeKey,
} from "./types";

export const TODAY = "2026-09-24";
export const TYPES: Record<TypeKey, string> = {
  llm: "LLM",
  embed: "Embedding",
  rerank: "Reranker",
  vision: "Vision",
  speech: "Speech",
  decision: "Decision model",
};
export const BENCH: Record<string, BenchDef> = {
  "CodeBench Pro": {
    unit: "% resolved",
    pct: true,
    d: 1,
    hi: true,
    types: ["llm"],
  },
  "TermTasks 4": {
    unit: "% tasks passed",
    pct: true,
    d: 1,
    hi: true,
    types: ["llm"],
  },
  ReasonHard: { unit: "% accuracy", pct: true, d: 1, hi: true, types: ["llm"] },
  "RetrievalEval v2": {
    unit: "nDCG@10",
    d: 3,
    hi: true,
    types: ["embed", "rerank"],
  },
  ChartRead: {
    unit: "% accuracy",
    pct: true,
    d: 1,
    hi: true,
    types: ["vision"],
  },
  VoxWER: {
    unit: "% word error rate",
    pct: true,
    d: 1,
    hi: false,
    types: ["speech"],
  },
  IntentRoute: { unit: "macro-F1", d: 2, hi: true, types: ["decision"] },
};
export const LABS: Record<string, LabDef> = {
  halden: {
    name: "Halden Labs",
    origin: "US",
    cloud: "Halden Cloud",
    regions: ["us-east", "eu-west"],
  },
  norrow: {
    name: "Norrow",
    origin: "EU",
    cloud: "Norrow Platform",
    regions: ["eu-west"],
  },
  kestrel: {
    name: "Kestrel AI",
    origin: "US",
    cloud: "Kestrel API",
    regions: ["us-east", "us-west"],
  },
  quillon: {
    name: "Quillon",
    origin: "UK",
    cloud: "Quillon Cloud",
    regions: ["uk-south"],
  },
  meridian: {
    name: "Meridian Compute",
    origin: "SG",
    cloud: "Meridian Cloud",
    regions: ["ap-southeast"],
  },
  oban: {
    name: "Oban Research",
    origin: "CA",
    cloud: "Oban API",
    regions: ["ca-central", "us-east"],
  },
};
export const HOSTS: Record<string, HostDef> = {
  stratus: {
    name: "Stratus",
    regions: ["us-east", "eu-west"],
    pm: 1.1,
    ttft: 80,
    tpsm: 0.95,
    ret: 0,
  },
  fernway: {
    name: "Fernway",
    regions: ["eu-west", "eu-central"],
    pm: 1.2,
    ttft: 120,
    tpsm: 0.9,
    ret: 0,
  },
  pylon: {
    name: "Pylon",
    regions: ["us-west", "ap-southeast"],
    pm: 1.3,
    ttftm: 0.6,
    tpsm: 1.8,
    ret: 30,
  },
  arcgrid: {
    name: "Arcgrid",
    regions: ["us-east"],
    pm: 0.8,
    ttft: 300,
    tpsm: 0.8,
    ret: "contract",
  },
};
const EVAL = "Harbor Evals";
type RawEvidence = Omit<Evidence, "who" | "src">;
const r = (
  b: string,
  v: number,
  ci: number | null,
  by: "lab" | "indep",
  date: string,
  effort = "default",
  harness = "standard",
): RawEvidence => ({ b, v, ci, by, date, effort, harness });

const RAW: [string, string, string, TypeKey, RawModel<RawEvidence>][] = [
  [
    "halden-atlas-3",
    "Atlas 3",
    "halden",
    "llm",
    {
      open: false,
      lic: "Proprietary",
      commercial: true,
      ctx: 1000000,
      rel: "2026-05-14",
      in: 3,
      out: 15,
      ttft: 900,
      tps: 85,
      hosts: ["stratus", "arcgrid"],
      bench: [
        r(
          "CodeBench Pro",
          66.1,
          null,
          "lab",
          "2026-05-14",
          "high",
          "Halden agent harness",
        ),
        r("CodeBench Pro", 62.4, 1.8, "indep", "2026-06-20"),
        r("TermTasks 4", 48.2, 2.5, "indep", "2026-06-22"),
        r("ReasonHard", 71.0, null, "lab", "2026-05-14"),
      ],
    },
  ],
  [
    "halden-atlas-3-mini",
    "Atlas 3 Mini",
    "halden",
    "llm",
    {
      open: false,
      lic: "Proprietary",
      commercial: true,
      ctx: 400000,
      rel: "2026-05-14",
      in: 0.4,
      out: 1.6,
      ttft: 350,
      tps: 190,
      hosts: ["stratus", "pylon", "arcgrid"],
      bench: [
        r("CodeBench Pro", 52.0, null, "lab", "2026-05-14"),
        r("CodeBench Pro", 49.8, 2.0, "indep", "2026-06-20"),
        r("TermTasks 4", 35.1, 2.8, "indep", "2026-06-22"),
        r("ReasonHard", 58.3, null, "lab", "2026-05-14"),
      ],
    },
  ],
  [
    "halden-atlas-2-5",
    "Atlas 2.5",
    "halden",
    "llm",
    {
      open: false,
      lic: "Proprietary",
      commercial: true,
      ctx: 200000,
      rel: "2025-09-02",
      status: "retired",
      retiredOn: "2026-03-31",
      in: 2.5,
      out: 10,
      ttft: 1100,
      tps: 60,
      hosts: ["stratus"],
      bench: [
        r("CodeBench Pro", 51.2, 2.1, "indep", "2025-10-11"),
        r("ReasonHard", 60.4, 1.9, "indep", "2025-10-11"),
      ],
    },
  ],
  [
    "halden-embed-3",
    "Halden Embed 3",
    "halden",
    "embed",
    {
      open: false,
      lic: "Proprietary",
      commercial: true,
      ctx: 32000,
      rel: "2026-02-03",
      in: 0.13,
      out: null,
      ttft: 120,
      tps: null,
      hosts: ["stratus"],
      bench: [
        r("RetrievalEval v2", 0.655, null, "lab", "2026-02-03"),
        r("RetrievalEval v2", 0.641, 0.008, "indep", "2026-03-01"),
      ],
    },
  ],
  [
    "norrow-fjord-l",
    "Fjord L",
    "norrow",
    "llm",
    {
      open: true,
      lic: "Apache-2.0",
      commercial: true,
      ctx: 256000,
      rel: "2026-04-08",
      in: 0.9,
      out: 2.7,
      ttft: 600,
      tps: 110,
      hosts: ["fernway", "stratus", "pylon"],
      bench: [
        r("CodeBench Pro", 57.0, null, "lab", "2026-04-08"),
        r("CodeBench Pro", 55.1, 2.0, "indep", "2026-05-02"),
        r("TermTasks 4", 40.2, 2.9, "indep", "2026-05-04"),
        r("ReasonHard", 64.0, null, "lab", "2026-04-08"),
      ],
    },
  ],
  [
    "norrow-fjord-s",
    "Fjord S",
    "norrow",
    "llm",
    {
      open: true,
      lic: "Apache-2.0",
      commercial: true,
      ctx: 128000,
      rel: "2026-04-08",
      in: 0.15,
      out: 0.45,
      ttft: 220,
      tps: 280,
      hosts: ["fernway", "pylon"],
      bench: [
        r("CodeBench Pro", 38.4, 2.4, "indep", "2026-05-02"),
        r("ReasonHard", 47.0, 2.2, "indep", "2026-05-02"),
      ],
    },
  ],
  [
    "norrow-fjord-code",
    "Fjord Code",
    "norrow",
    "llm",
    {
      open: true,
      lic: "Norrow Community Licence",
      commercial: true,
      ctx: 256000,
      rel: "2026-07-01",
      in: 0.6,
      out: 1.8,
      ttft: 480,
      tps: 140,
      hosts: ["fernway", "stratus", "arcgrid"],
      bench: [
        r("CodeBench Pro", 60.5, null, "lab", "2026-07-01"),
        r("CodeBench Pro", 57.9, 2.2, "indep", "2026-07-19"),
        r("TermTasks 4", 43.0, null, "lab", "2026-07-01"),
      ],
    },
  ],
  [
    "norrow-fjord-embed",
    "Fjord Embed",
    "norrow",
    "embed",
    {
      open: true,
      lic: "Apache-2.0",
      commercial: true,
      ctx: 32000,
      rel: "2026-04-08",
      in: 0.05,
      out: null,
      ttft: 140,
      tps: null,
      hosts: ["fernway"],
      bench: [r("RetrievalEval v2", 0.618, 0.009, "indep", "2026-05-02")],
    },
  ],
  [
    "norrow-gate-1",
    "Gate-1",
    "norrow",
    "decision",
    {
      open: true,
      lic: "Apache-2.0",
      commercial: true,
      ctx: 32000,
      rel: "2026-06-10",
      in: 0.05,
      out: 0.2,
      ttft: 150,
      tps: 400,
      hosts: ["fernway"],
      bench: [r("IntentRoute", 0.88, null, "lab", "2026-06-10")],
    },
  ],
  [
    "kestrel-talon-2",
    "Talon 2",
    "kestrel",
    "llm",
    {
      open: false,
      lic: "Proprietary",
      commercial: true,
      ctx: 500000,
      rel: "2026-06-03",
      in: 0.7,
      out: 2.8,
      ttft: 700,
      tps: 120,
      hosts: ["stratus", "pylon"],
      bench: [
        r("CodeBench Pro", 61.0, null, "lab", "2026-06-03", "high"),
        r("CodeBench Pro", 57.4, 2.1, "indep", "2026-06-28"),
        r("TermTasks 4", 44.6, 2.6, "indep", "2026-06-29"),
        r("ReasonHard", 69.0, null, "lab", "2026-06-03"),
      ],
    },
  ],
  [
    "kestrel-talon-2-flash",
    "Talon 2 Flash",
    "kestrel",
    "llm",
    {
      open: false,
      lic: "Proprietary",
      commercial: true,
      ctx: 500000,
      rel: "2026-06-03",
      in: 0.25,
      out: 1.0,
      ttft: 250,
      tps: 320,
      hosts: ["stratus", "pylon"],
      bench: [
        r("CodeBench Pro", 44.0, 2.3, "indep", "2026-06-28"),
        r("TermTasks 4", 31.0, 2.9, "indep", "2026-06-29"),
      ],
    },
  ],
  [
    "kestrel-talon-2-deep",
    "Talon 2 Deep",
    "kestrel",
    "llm",
    {
      open: false,
      lic: "Proprietary",
      commercial: true,
      ctx: 500000,
      rel: "2026-06-03",
      in: 5,
      out: 25,
      ttft: 1800,
      tps: 55,
      hosts: ["stratus"],
      bench: [
        r("CodeBench Pro", 67.2, null, "lab", "2026-06-03", "high"),
        r("CodeBench Pro", 63.1, 1.9, "indep", "2026-06-28", "high"),
        r("ReasonHard", 76.5, 1.5, "indep", "2026-06-29", "high"),
      ],
    },
  ],
  [
    "kestrel-wren-7b",
    "Wren 7B",
    "kestrel",
    "llm",
    {
      open: true,
      lic: "MIT",
      commercial: true,
      ctx: 32000,
      rel: "2026-03-12",
      in: 0.05,
      out: 0.2,
      ttft: 150,
      tps: 400,
      hosts: ["pylon", "arcgrid"],
      bench: [
        r("CodeBench Pro", 21.3, null, "lab", "2026-03-12"),
        r("ReasonHard", 30.0, null, "lab", "2026-03-12"),
      ],
    },
  ],
  [
    "kestrel-rerank-2",
    "Rerank 2",
    "kestrel",
    "rerank",
    {
      open: false,
      lic: "Proprietary",
      commercial: true,
      ctx: 32000,
      rel: "2026-01-20",
      in: 0.05,
      out: null,
      ttft: 180,
      tps: null,
      hosts: ["stratus"],
      bench: [
        r(
          "RetrievalEval v2",
          0.702,
          0.007,
          "indep",
          "2026-02-14",
          "default",
          "rerank top-100 from BM25",
        ),
      ],
    },
  ],
  [
    "quillon-q-prime",
    "Q-Prime",
    "quillon",
    "llm",
    {
      open: false,
      lic: "Proprietary",
      commercial: true,
      ctx: 2000000,
      rel: "2026-04-22",
      in: 15,
      out: 75,
      ttft: 2500,
      tps: 35,
      hosts: ["stratus"],
      bench: [
        r("CodeBench Pro", 68.0, null, "lab", "2026-04-22", "high"),
        r("CodeBench Pro", 65.8, 1.6, "indep", "2026-05-15"),
        r("TermTasks 4", 52.3, 2.4, "indep", "2026-05-16"),
        r("ReasonHard", 79.1, 1.4, "indep", "2026-05-16"),
      ],
    },
  ],
  [
    "quillon-q-swift",
    "Q-Swift",
    "quillon",
    "llm",
    {
      open: false,
      lic: "Proprietary",
      commercial: true,
      ctx: 200000,
      rel: "2026-04-22",
      in: 0.8,
      out: 3.2,
      ttft: 400,
      tps: 160,
      hosts: ["stratus"],
      fpRegions: null,
      hostRegions: ["us-east"],
      bench: [
        r("CodeBench Pro", 50.5, 2.2, "indep", "2026-05-15"),
        r("TermTasks 4", 38.0, null, "lab", "2026-04-22"),
      ],
    },
  ],
  [
    "quillon-q-edge-3b",
    "Q-Edge 3B",
    "quillon",
    "llm",
    {
      open: true,
      lic: "Quillon Open Licence (non-commercial)",
      commercial: false,
      ctx: 32000,
      rel: "2026-02-11",
      in: 0.06,
      out: 0.24,
      ttft: 160,
      tps: 380,
      hosts: ["pylon"],
      bench: [r("CodeBench Pro", 18.2, 2.5, "indep", "2026-03-05")],
    },
  ],
  [
    "meridian-tide-4",
    "Tide 4",
    "meridian",
    "llm",
    {
      open: true,
      lic: "Tide Licence v2",
      commercial: true,
      ctx: 256000,
      rel: "2026-05-30",
      in: 0.35,
      out: 1.2,
      ttft: 800,
      tps: 90,
      hosts: ["pylon", "stratus", "arcgrid"],
      fpRet: null,
      bench: [
        r("CodeBench Pro", 53.0, 2.6, "indep", "2026-06-25"),
        r("TermTasks 4", 37.5, 3.0, "indep", "2026-06-26"),
        r("ReasonHard", 62.0, null, "lab", "2026-05-30"),
      ],
    },
  ],
  [
    "meridian-tide-4-reason",
    "Tide 4 Reason",
    "meridian",
    "llm",
    {
      open: true,
      lic: "Tide Licence v2",
      commercial: true,
      ctx: 128000,
      rel: "2026-05-30",
      in: 0.7,
      out: 2.8,
      ttft: 2100,
      tps: 45,
      hosts: ["pylon"],
      bench: [
        r("CodeBench Pro", 56.2, 2.4, "indep", "2026-06-25", "high"),
        r("ReasonHard", 74.0, 1.8, "indep", "2026-06-26", "high"),
      ],
    },
  ],
  [
    "meridian-tide-4-mini",
    "Tide 4 Mini",
    "meridian",
    "llm",
    {
      open: true,
      lic: "Tide Licence v2",
      commercial: true,
      ctx: 64000,
      rel: "2026-05-30",
      in: 0.08,
      out: 0.3,
      ttft: 200,
      tps: 300,
      hosts: ["pylon"],
      bench: [r("CodeBench Pro", 30.2, 2.7, "indep", "2026-06-25")],
    },
  ],
  [
    "meridian-anchor-embed",
    "Anchor Embed",
    "meridian",
    "embed",
    {
      open: true,
      lic: "Tide Licence v2",
      commercial: true,
      ctx: 32000,
      rel: "2026-03-18",
      in: 0.06,
      out: null,
      ttft: 160,
      tps: null,
      hosts: [],
      fpRegions: null,
      bench: [r("RetrievalEval v2", 0.598, 0.01, "indep", "2026-04-10")],
    },
  ],
  [
    "meridian-lens-2",
    "Lens 2",
    "meridian",
    "vision",
    {
      open: false,
      lic: "Proprietary",
      commercial: true,
      ctx: 128000,
      rel: "2026-07-14",
      in: 1.2,
      out: 4.8,
      ttft: 650,
      tps: 95,
      hosts: ["stratus"],
      bench: [
        r("ChartRead", 84.0, null, "lab", "2026-07-14"),
        r("ChartRead", 81.2, 1.5, "indep", "2026-08-02"),
      ],
    },
  ],
  [
    "oban-cairn-1",
    "Cairn 1",
    "oban",
    "llm",
    {
      open: false,
      lic: "Proprietary",
      commercial: true,
      ctx: 1000000,
      rel: "2026-09-22",
      provisional: true,
      in: 1.0,
      out: 4.0,
      ttft: null,
      tps: null,
      hosts: [],
      bench: [
        r(
          "CodeBench Pro",
          64.0,
          null,
          "lab",
          "2026-09-22",
          "high",
          "Oban agent harness",
        ),
        r("TermTasks 4", 51.0, null, "lab", "2026-09-22", "high"),
        r("ReasonHard", 76.0, null, "lab", "2026-09-22", "high"),
      ],
    },
  ],
  [
    "oban-birch",
    "Birch",
    "oban",
    "llm",
    {
      open: false,
      lic: "Proprietary",
      commercial: true,
      ctx: 128000,
      rel: "2026-01-28",
      in: 0.3,
      out: 1.2,
      ttft: 300,
      tps: 210,
      hosts: ["stratus"],
      bench: [
        r("CodeBench Pro", 41.7, 2.3, "indep", "2026-02-20"),
        r("ReasonHard", 55.0, 2.1, "indep", "2026-02-20"),
      ],
    },
  ],
  [
    "oban-echo",
    "Echo",
    "oban",
    "speech",
    {
      open: false,
      lic: "Proprietary",
      commercial: true,
      ctx: null,
      rel: "2026-04-30",
      in: 0.5,
      out: 2.0,
      ttft: 300,
      tps: null,
      hosts: [],
      bench: [r("VoxWER", 5.8, 0.3, "indep", "2026-05-21")],
    },
  ],
];

const rp = (x: number) => Number(x.toPrecision(2));
const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-");
export function buildCatalogue(): Catalogue {
  const models = RAW.map(([id, name, lab, type, o]) => {
    const L = LABS[lab];
    const base = {
      id,
      name,
      lab,
      labName: L.name,
      origin: L.origin,
      type,
      status: "active" as const,
      ...o,
    };
    const bench: Evidence[] = base.bench.map((x) => ({
      ...x,
      who: x.by === "indep" ? EVAL : L.name,
      src:
        x.by === "indep"
          ? `https://harbor-evals.example/${slug(x.b)}/${id}`
          : `https://${lab}.example/research/${id}`,
    }));
    const offs: Offering[] = [
      {
        id: id + "@fp",
        provider: L.cloud,
        first: true,
        regions: base.fpRegions === undefined ? L.regions : base.fpRegions,
        in: base.in,
        out: base.out,
        ttft: base.ttft,
        tps: base.tps,
        ret: base.fpRet === undefined ? 30 : base.fpRet,
      },
    ];
    (base.hosts || []).forEach((h) => {
      const H = HOSTS[h];
      offs.push({
        id: id + "@" + h,
        provider: H.name,
        regions: base.hostRegions || H.regions,
        in: rp(base.in * H.pm),
        out: base.out == null ? null : rp(base.out * H.pm),
        ttft:
          base.ttft == null
            ? null
            : Math.round(
                H.ttftm ? base.ttft * H.ttftm : base.ttft + (H.ttft ?? 0),
              ),
        tps: base.tps == null ? null : Math.round(base.tps * H.tpsm),
        ret: H.ret,
      });
    });
    const m: Model = { ...base, bench, offerings: offs };
    return m;
  });
  const byId = Object.fromEntries(models.map((m) => [m.id, m]));
  return {
    models,
    byId,
    offerings: models.reduce((a, m) => a + m.offerings.length, 0),
    labs: Object.keys(LABS).length,
  };
}

export const TEMPLATES: Template[] = [
  {
    id: "budget-agent",
    name: "Coding agent on a budget",
    task: "Coding agent that fixes failing tests in a TypeScript monorepo",
    spec: {
      tokIn: 60000,
      tokOut: 6000,
      bench: "CodeBench Pro",
      w: { cap: 0.5, cost: 0.4, speed: 0.1 },
      conds: [
        { f: "type", v: "llm" },
        { f: "active" },
        { f: "ctx", min: 128000 },
        { f: "task$", max: 0.1 },
        { f: "bench", b: "CodeBench Pro", min: 45, indep: true },
      ],
    },
  },
  {
    id: "private",
    name: "Private and on-prem",
    task: "Internal assistant we run on our own servers",
    spec: {
      tokIn: 20000,
      tokOut: 2000,
      bench: "CodeBench Pro",
      w: { cap: 0.6, cost: 0.2, speed: 0.2 },
      conds: [
        { f: "type", v: "llm" },
        { f: "active" },
        { f: "open", v: true },
        { f: "commercial" },
        { f: "ctx", min: 128000 },
      ],
    },
  },
  {
    id: "embed",
    name: "Cheapest good embedding",
    task: "Embed 10,000 documents of about 800 tokens for retrieval",
    spec: {
      tokIn: 8000000,
      tokOut: 0,
      bench: "RetrievalEval v2",
      w: { cap: 0.3, cost: 0.7, speed: 0 },
      conds: [
        { f: "type", v: "embed" },
        { f: "active" },
        { f: "bench", b: "RetrievalEval v2", min: 0.6, indep: true },
      ],
    },
  },
];

export const FACETS: Facet[] = [
  {
    k: "context length window tokens",
    label: "Context length",
    hint: "minimum, tokens",
    c: { f: "ctx", min: 200000 },
  },
  {
    k: "open weights licence self host",
    label: "Open weights",
    hint: "require or exclude",
    c: { f: "open", v: true },
  },
  {
    k: "licence license commercial use",
    label: "Licence allows commercial use",
    hint: "yes / no / unknown",
    c: { f: "commercial" },
  },
  {
    k: "price per task budget cost dollars",
    label: "Price per task",
    hint: "$ per task, from your token counts",
    c: { f: "task$", max: 0.1 },
  },
  {
    k: "input price per million tokens cost",
    label: "Input price",
    hint: "$ per 1M input tokens",
    c: { f: "in$", max: 1 },
  },
  {
    k: "data residency region eu gdpr location",
    label: "Data residency: EU",
    hint: "offering serves an EU region",
    c: { f: "resid", v: "EU" },
  },
  {
    k: "data residency region us location",
    label: "Data residency: US",
    hint: "offering serves a US region",
    c: { f: "resid", v: "US" },
  },
  {
    k: "data retention zero privacy logging",
    label: "Data retention: 0 days",
    hint: "provider terms",
    c: { f: "ret0" },
  },
  {
    k: "benchmark floor codebench pro score coding",
    label: "CodeBench Pro floor",
    hint: "% resolved, independent",
    c: { f: "bench", b: "CodeBench Pro", min: 50, indep: true },
  },
  {
    k: "benchmark termtasks terminal",
    label: "TermTasks 4 floor",
    hint: "% tasks passed",
    c: { f: "bench", b: "TermTasks 4", min: 40, indep: true },
  },
  {
    k: "benchmark reasonhard reasoning math",
    label: "ReasonHard floor",
    hint: "% accuracy",
    c: { f: "bench", b: "ReasonHard", min: 60, indep: true },
  },
  {
    k: "latency time to first token ttft speed",
    label: "Time to first token",
    hint: "maximum, ms",
    c: { f: "ttft", max: 1000 },
  },
  {
    k: "throughput speed tokens per second",
    label: "Output throughput",
    hint: "minimum, tokens/s",
    c: { f: "tps", min: 100 },
  },
  {
    k: "origin jurisdiction country lab",
    label: "Origin jurisdiction",
    hint: "exclude SG",
    c: { f: "origin", ex: ["SG"] },
  },
  {
    k: "relative compare better cheaper than talon",
    label: "At least as good as Talon 2, and cheaper",
    hint: "relative, on CodeBench Pro",
    c: { f: "rel", ref: "kestrel-talon-2", b: "CodeBench Pro" },
  },
];
