"""Generate `api/worker/openapi.yaml` from the rank endpoint's own code (MODEL-72).

The spec is **not** written by hand. Everything a caller could build a wrong
request from — the accepted fields, the enums, the limits, the status codes, the
error codes, the shape of a ranked row — is read out of the implementation:

* the request vocabulary comes from `rank_service` and `api.ranking.engine`
  (`USE_CASE_PROFILES`, `HOSTING_MODES`, `KNOWN_RUNTIMES`, `MAX_LIMIT`,
  `MAX_BODY_BYTES`, the `HTTP_*` constants);
* every response schema is **inferred from a real response**: this module builds
  a small synthetic export, calls `rank_service.rank` and
  `rank_service.error_response`, and describes the bodies that come back. The
  ranked rows are `pipeline.ranking.rank_report` rows, so a field added to the
  scorer appears in the spec on the next generation with nobody editing YAML;
* the error codes are cross-checked against the source. `_probe_errors` walks
  the syntax tree of `rank_service.py` and `entry.py` for every code either file
  can emit, and generation **fails** if one of them is not exercised here. A new
  refusal cannot be added to the Worker without appearing in the spec.

Only prose is hand-written, in `DESCRIPTIONS`, keyed by the path of the field it
describes. A description that names a field the implementation no longer has
also fails generation.

    python api/worker/openapi.py              # write api/worker/openapi.yaml
    python api/worker/openapi.py --check      # fail if the committed file drifted
    python api/worker/openapi.py --probe https://api.modelspec.dev
        # build a request from the committed spec ALONE, send it to a live
        # service, and validate the answer against the spec's own schemas

`--probe` deliberately imports nothing from this repository once the YAML is
loaded: it is the proof that a caller holding only the spec can make a call that
works. CI runs `--check` on every pull request and `--probe` against
api.modelspec.dev after a deploy.

The access layer (MODEL-69: keys, tiers, quotas, the `test_` sandbox) is *not*
in the spec. It is built but not yet wired into the Worker, and a spec that
required an `Authorization` header would describe a service that does not exist.
`x-modelspec-not-yet-live` records that, sourced from `tiers.json`, so the gap is
machine-readable rather than merely absent.
"""

from __future__ import annotations

import argparse
import ast
import importlib.util
import json
import sys
import urllib.request
from pathlib import Path
from typing import Any

import yaml

WORKER_ROOT = Path(__file__).resolve().parent
REPO_ROOT = WORKER_ROOT.parents[1]
SRC = WORKER_ROOT / "src"
SPEC_PATH = WORKER_ROOT / "openapi.yaml"
TIERS_PATH = WORKER_ROOT / "tiers.json"

HEADER = (
    "# GENERATED BY api/worker/openapi.py — DO NOT EDIT BY HAND.\n"
    "# Regenerate with `python api/worker/openapi.py`; CI runs `--check`.\n"
    "# The schemas below are inferred from responses produced by the Worker's\n"
    "# own code, so this file cannot describe an endpoint that does not exist.\n"
)

SERVER_URL = "https://api.modelspec.dev"

#: Sent by `--probe`, and documented, because the host sits behind Cloudflare
#: and the standard-library default user agent (`Python-urllib/*`) is refused at
#: the edge with a non-JSON `error code: 1010` body that no client expects.
USER_AGENT = "modelspec-openapi-probe (+https://github.com/turbobeest/modelspec)"

#: The one request used as the spec's example. It is also what `--probe` sends,
#: so the example in the document is a request that is known to work.
EXAMPLE_REQUEST: dict[str, Any] = {
    "use_case": "coding",
    "environment": {"hosting": "managed_api"},
    "constraints": {"price_sensitivity": 0.25},
    "limit": 3,
}


def _load(name: str):
    """Import a Worker module from its path; it is not an installed package."""
    if str(REPO_ROOT) not in sys.path:
        sys.path.insert(0, str(REPO_ROOT))
    spec = importlib.util.spec_from_file_location(f"modelspec_worker_{name}", SRC / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


service = _load("rank_service")
sandbox = _load("access_sandbox")


# ── prose, the only hand-written part ────────────────────────────────────────

#: Keyed by `<schema>.<dotted field path>`. Every key must name a field the
#: generated schemas actually carry; `build_spec` raises otherwise.
DESCRIPTIONS: dict[str, str] = {
    "RankRequest.use_case": "Which profile scores the candidates. Required.",
    "RankRequest.environment.hardware": (
        "A device id from https://modelspec.dev/api/rank/hardware.json. Keeps only models "
        "whose weights fit that device. An id not in that file is a 400, never 'nothing fits'."
    ),
    "RankRequest.environment.hosting": "Where the model runs.",
    "RankRequest.environment.runtime": (
        "The serving stack. A local runtime implies downloadable weights; every other value "
        "is recorded and reported in applied.unbound, because the export carries no "
        "runtime-level evidence to filter on."
    ),
    "RankRequest.constraints.open_weights": "Keep only models whose weights can be downloaded.",
    "RankRequest.constraints.max_cost_per_million_input_tokens": (
        "USD ceiling on input cost. Applied before scoring. A model with no published price "
        "is dropped by this filter rather than assumed cheap."
    ),
    "RankRequest.constraints.price_sensitivity": (
        "0–1. How much cost weighs against quality. Every shipped profile weights cost at 0, "
        "so this is the only way to make price matter."
    ),
    "RankRequest.constraints.include_rehosts": (
        "Include models that are rehosts of another provider's weights."
    ),
    "RankRequest.limit": "Caps the ranked shortlist only, not the pool.",
    "RankResponse.build": "The published export this answer was computed from.",
    "RankResponse.service_commit": "The sha of the deployed Worker. Fixed per deployment.",
    "RankResponse.request": "The request as received and normalised.",
    "RankResponse.applied": "What actually bound. Read applied.unbound before trusting a filter.",
    "RankResponse.applied.unbound": (
        "Fields that were accepted, recorded, and filtered nothing, each with the reason. "
        "An empty list means every field you sent bound."
    ),
    "RankResponse.policy": "The evidence floors this answer was ordered under.",
    "RankResponse.ranking_status": (
        "Whether every candidate could be ordered. `partial` is the normal state of the "
        "catalogue, not a degraded answer."
    ),
    "RankResponse.result": "The shortlist, best first. Never empty on a 200.",
    "RankedModel.score": "Composite, 0–100, on the conservative lower bound.",
    "RankedModel.evidence_basis": (
        "Provenance of the benchmark inputs — none, unverified-legacy, mixed, "
        "partial-verified or verified. Not a quality verdict, and 'verified' is not a "
        "certificate."
    ),
    "RankedModel.benchmark_coverage": (
        "Share of the profile's weighted benchmarks this model has a score for."
    ),
    "RankedModel.missing_benchmarks": "Benchmarks the profile weighs that this model lacks.",
    "RankedModel.cost_input": "USD per million input tokens, or null when unpublished.",
    "NoMatchError.eliminated_by": "The first filter whose survivor count reached zero.",
    "NoMatchError.elimination_trace": "Every filter, in the order the scorer applies them.",
    "NoMatchError.relax": "The field to change. Acting on this is the whole point of the 422.",
    "RequestRefusedError.accepted": "The values this field does accept.",
}


# ── a catalogue to answer from ───────────────────────────────────────────────

def _export(use_case: str = "coding", *, only_unrated: bool = False) -> dict[str, Any]:
    """A candidates export in the published shape, from the sandbox fixtures.

    Reusing `access_sandbox._candidates` rather than inventing a second set of
    fixtures keeps this honest in the way that matters: these are
    `pipeline.ranking.Candidate` records, and what comes back out is a
    `rank_report` row with every field a live row has.
    """
    pool = sandbox._candidates(use_case)
    if only_unrated:
        pool = [c for c in pool if not c.benchmark_scores]
    return {
        "build": {
            "commit": "0" * 40,
            "built_at": "2026-01-01T00:00:00+00:00",
            "eligibility_as_of": "2026-01-01",
            "export_schema_version": "2.0",
        },
        "candidates": [
            {
                "model_id": c.model_id, "display_name": c.display_name, "provider": c.provider,
                "model_type": c.model_type, "model_subtypes": list(c.model_subtypes),
                "benchmark_scores": dict(c.benchmark_scores),
                "capability_tiers": dict(c.capability_tiers),
                "cost_input": c.cost_input, "context_window": c.context_window,
                "open_weights": c.open_weights, "scores_as_of": c.scores_as_of,
                "fits": {"example_device": True} if c.open_weights else {},
                "verified_benchmarks": sorted(c.verified_benchmarks),
                "rehost_of": c.rehost_of,
            }
            for c in pool
        ],
    }


_HARDWARE = {"hardware": [{"id": "example_device"}]}
_COMMIT = "0" * 40
_ORIGIN = "https://modelspec.dev"


def _answer(payload: dict[str, Any], **kw: Any) -> dict[str, Any]:
    """One response body, produced by the endpoint's own code."""
    export = _export(**kw)
    try:
        _status, body = service.rank(payload, export, _HARDWARE, _COMMIT, _ORIGIN)
    except service.RequestError as exc:
        _status, body = service.error_response(exc, export, _COMMIT, _ORIGIN)
    return body


# ── every refusal, cross-checked against the source ──────────────────────────

#: One payload per error code `rank_service` can raise. `_probe_errors` fails if
#: the source gains a code that is not exercised here.
_ERROR_PROBES: dict[str, dict[str, Any]] = {
    "invalid_request": {"use_case": "coding", "not_a_field": 1},
    "unknown_use_case": {"use_case": "not_a_use_case"},
    "unknown_hardware": {"use_case": "coding", "environment": {"hardware": "not_a_device"}},
    "unknown_hosting": {"use_case": "coding", "environment": {"hosting": "not_a_mode"}},
    "unknown_runtime": {"use_case": "coding", "environment": {"runtime": "not_a_runtime"}},
    "no_match": {"use_case": "coding",
                 "constraints": {"max_cost_per_million_input_tokens": 0.0}},
    "insufficient_evidence": {"use_case": "coding"},
}

#: Codes raised by the transport in `entry.py`, which cannot be driven from
#: CPython (it imports the Workers runtime). Their statuses are read out of its
#: syntax tree by `entry_error_codes`, not asserted here.
_ENTRY_ONLY = {"not_found", "method_not_allowed", "payload_too_large", "export_unavailable"}


def source_error_codes() -> set[str]:
    """Every `error.code` string either Worker module can emit.

    Read from the syntax tree rather than from a list kept beside it, so that
    adding a refusal to the Worker and forgetting the docs is a failed build.
    """
    codes: set[str] = set()
    for path in (SRC / "rank_service.py", SRC / "entry.py"):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            # RequestError("code", "message", ...)
            if isinstance(node, ast.Call):
                name = node.func.id if isinstance(node.func, ast.Name) else None
                if name == "RequestError" and node.args and isinstance(node.args[0], ast.Constant):
                    codes.add(str(node.args[0].value))
            # {"code": "...", ...}
            if isinstance(node, ast.Dict):
                for key, value in zip(node.keys, node.values):
                    if (isinstance(key, ast.Constant) and key.value == "code"
                            and isinstance(value, ast.Constant) and isinstance(value.value, str)):
                        codes.add(value.value)
    return codes


def entry_error_codes() -> dict[str, int]:
    """`code -> HTTP status` for the refusals `entry.py` writes directly."""
    tree = ast.parse((SRC / "entry.py").read_text(encoding="utf-8"))
    found: dict[str, int] = {}
    for node in ast.walk(tree):
        if not (isinstance(node, ast.Call) and isinstance(node.func, ast.Name)
                and node.func.id == "_json_response" and len(node.args) == 2):
            continue
        status_node, body_node = node.args
        if not (isinstance(status_node, ast.Attribute)
                and status_node.attr.startswith("HTTP_")
                and isinstance(body_node, ast.Dict)):
            continue
        status = getattr(service, status_node.attr, None)
        for key, value in zip(body_node.keys, body_node.values):
            if not (isinstance(key, ast.Constant) and key.value == "error"
                    and isinstance(value, ast.Dict)):
                continue
            for inner_key, inner_value in zip(value.keys, value.values):
                if (isinstance(inner_key, ast.Constant) and inner_key.value == "code"
                        and isinstance(inner_value, ast.Constant) and isinstance(status, int)):
                    found[str(inner_value.value)] = status
    return found


def returned_strings(path: Path, function: str) -> list[str]:
    """Every string literal `function` can return, read from its syntax tree.

    `ranking_status`, `rank_status` and `evidence_basis` are closed vocabularies
    a caller branches on, and they are produced by three small functions in the
    scorer. Reading them out of the source beats copying them into this file,
    which is the mistake the whole module exists to avoid.
    """
    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == function:
            found = {
                literal.value
                for child in ast.walk(node) if isinstance(child, ast.Return) and child.value
                for literal in ast.walk(child.value)
                # `return "partial" if ranked else "unavailable"` is two of them.
                if isinstance(literal, ast.Constant) and isinstance(literal.value, str)
            }
            if found:
                return sorted(found)
    raise SystemExit(f"{function} in {path.name} no longer returns string literals; "
                     f"the enum in {Path(__file__).name} cannot be derived")


def dict_key_strings(path: Path, function: str, key: str) -> list[str]:
    """Every string a `{"<key>": ...}` entry inside `function` can carry."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in ast.walk(tree):
        if not (isinstance(node, ast.FunctionDef) and node.name == function):
            continue
        for child in ast.walk(node):
            if not isinstance(child, ast.Dict):
                continue
            for dict_key, dict_value in zip(child.keys, child.values):
                if not (isinstance(dict_key, ast.Constant) and dict_key.value == key):
                    continue
                found = {literal.value for literal in ast.walk(dict_value)
                         if isinstance(literal, ast.Constant) and isinstance(literal.value, str)}
                if found:
                    return sorted(found)
    raise SystemExit(f"{function} in {path.name} no longer builds a {key!r} entry from string "
                     f"literals; the enum in {Path(__file__).name} cannot be derived")


_ENGINE = REPO_ROOT / "api" / "ranking" / "engine.py"

#: `field name -> how to read its permitted values out of the implementation`.
VOCABULARIES: dict[str, Any] = {
    "ranking_status": lambda: returned_strings(_ENGINE, "_ranking_status"),
    "evidence_basis": lambda: returned_strings(REPO_ROOT / "pipeline" / "ranking.py", "_basis"),
    "rank_status": lambda: dict_key_strings(_ENGINE, "_benchmark_evidence", "rank_status"),
}


def _apply_vocabularies(schema: dict[str, Any], name: str | None = None) -> dict[str, Any]:
    """Attach the derived enums wherever those field names appear."""
    if name in VOCABULARIES and schema.get("type") == "string":
        schema = {**schema, "enum": VOCABULARIES[name]()}
    for key, child in (schema.get("properties") or {}).items():
        schema["properties"][key] = _apply_vocabularies(child, key)
    if isinstance(schema.get("items"), dict):
        schema["items"] = _apply_vocabularies(schema["items"], None)
    return schema


def _probe_errors() -> dict[str, tuple[int, dict[str, Any]]]:
    """Run every refusal and keep what came back. Nothing here is written down."""
    out: dict[str, tuple[int, dict[str, Any]]] = {}
    for code, payload in _ERROR_PROBES.items():
        kw = {"only_unrated": True} if code == "insufficient_evidence" else {}
        export = _export(**kw)
        try:
            status, body = service.rank(payload, export, _HARDWARE, _COMMIT, _ORIGIN)
        except service.RequestError as exc:
            status, body = service.error_response(exc, export, _COMMIT, _ORIGIN)
        got = (body.get("error") or {}).get("code")
        if got != code:
            raise SystemExit(
                f"the probe for {code!r} produced {got!r} instead; fix _ERROR_PROBES "
                f"in {Path(__file__).name} before regenerating the spec")
        out[code] = (status, body)

    missing = source_error_codes() - set(out) - _ENTRY_ONLY
    if missing:
        raise SystemExit(
            "the Worker can return error code(s) the spec would not document: "
            + ", ".join(sorted(missing))
            + f". Add a payload to _ERROR_PROBES in {Path(__file__).name}.")
    return out


# ── schema inference ─────────────────────────────────────────────────────────

def _infer(value: Any) -> dict[str, Any]:
    """Describe one JSON value. Deterministic: keys are emitted sorted."""
    if value is None:
        return {"nullable": True}
    if isinstance(value, bool):
        return {"type": "boolean"}
    if isinstance(value, int):
        return {"type": "integer"}
    if isinstance(value, float):
        return {"type": "number"}
    if isinstance(value, str):
        return {"type": "string"}
    if isinstance(value, list):
        schema: dict[str, Any] = {"type": "array"}
        item: dict[str, Any] = {}
        for entry in value:
            item = _merge(item, _infer(entry))
        schema["items"] = item or {}
        return schema
    if isinstance(value, dict):
        properties = {key: _infer(value[key]) for key in sorted(value)}
        return {"type": "object", "required": sorted(value), "properties": properties}
    raise TypeError(f"cannot describe {type(value).__name__}")


def _merge(left: dict[str, Any], right: dict[str, Any]) -> dict[str, Any]:
    """Union two inferred schemas from two sample responses.

    A field seen null in one sample and typed in another is that type, nullable.
    `required` is the intersection: a field one sample omits is optional.
    """
    if not left:
        return dict(right)
    if not right:
        return dict(left)
    out: dict[str, Any] = {}
    nullable = bool(left.get("nullable") or right.get("nullable"))
    type_ = left.get("type") or right.get("type")
    if left.get("type") and right.get("type") and left["type"] != right["type"]:
        # integer and number are the same field seen with and without a fraction.
        type_ = "number" if {left["type"], right["type"]} == {"integer", "number"} else "string"
    if type_:
        out["type"] = type_
    if nullable:
        out["nullable"] = True
    if type_ == "object":
        keys = sorted(set(left.get("properties", {})) | set(right.get("properties", {})))
        out["properties"] = {
            key: _merge(left.get("properties", {}).get(key, {}),
                        right.get("properties", {}).get(key, {}))
            for key in keys
        }
        required = sorted(set(left.get("required", [])) & set(right.get("required", [])))
        if required:
            out["required"] = required
    if type_ == "array":
        out["items"] = _merge(left.get("items", {}), right.get("items", {}))
    return out


def _describe(schema: dict[str, Any], prefix: str, used: set[str]) -> dict[str, Any]:
    """Attach the hand-written prose to the generated schema, by field path."""
    text = DESCRIPTIONS.get(prefix)
    if text:
        schema = {"description": text, **schema}
        used.add(prefix)
    for key, child in (schema.get("properties") or {}).items():
        schema["properties"][key] = _describe(child, f"{prefix}.{key}", used)
    if isinstance(schema.get("items"), dict) and schema["items"].get("properties"):
        # `[]` so an array's own prose is not repeated onto each element.
        schema["items"] = _describe(schema["items"], f"{prefix}[]", used)
    return schema


# ── the document ─────────────────────────────────────────────────────────────

def _request_schema() -> dict[str, Any]:
    """The request, from the parser's own vocabulary. Nothing typed twice."""
    hosting = {mode: str(meta["means"]) for mode, meta in sorted(service.HOSTING_MODES.items())}
    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["use_case"],
        "properties": {
            "use_case": {"type": "string", "enum": sorted(service.USE_CASE_PROFILES)},
            "environment": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "hardware": {"type": "string", "nullable": True},
                    # `null` rides in each enum because the parser accepts an
                    # explicit null as "not stated", and OpenAPI 3.0 reads an
                    # enum as the whole permitted set even when nullable.
                    "hosting": {"type": "string", "nullable": True,
                                "enum": [*sorted(hosting), None],
                                "x-meaning": hosting},
                    "runtime": {"type": "string", "nullable": True,
                                "enum": [*sorted(service.KNOWN_RUNTIMES), None],
                                "x-implies-open-weights": sorted(service.LOCAL_RUNTIMES)},
                },
            },
            "constraints": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "open_weights": {"type": "boolean", "nullable": True},
                    "max_cost_per_million_input_tokens": {"type": "number", "minimum": 0,
                                                          "nullable": True},
                    "price_sensitivity": {"type": "number", "minimum": 0, "maximum": 1,
                                          "default": 0.0},
                    "include_rehosts": {"type": "boolean", "default": False},
                },
            },
            "limit": {"type": "integer", "minimum": 0, "maximum": service.MAX_LIMIT,
                      "default": service.DEFAULT_LIMIT},
        },
    }


def _not_yet_live() -> dict[str, Any]:
    """The access layer, recorded as built-but-unwired rather than promised."""
    tiers = json.loads(TIERS_PATH.read_text(encoding="utf-8"))
    return {
        "status": "implemented but NOT wired into the deployed Worker",
        "ticket": "MODEL-69",
        "effect_today": (
            "/v1/rank takes no key, meters nothing and never returns 401, 403 or 429. "
            "Do not build a client that depends on those statuses yet; do build one that "
            "tolerates them."
        ),
        "when_wired": {
            "present_key_as": ["Authorization: Bearer <key>", "X-API-Key: <key>"],
            "never": "a key in the query string",
            "policy_version": tiers["policy_version"],
            "sandbox_prefix": tiers["sandbox_prefix"],
            "timezone": tiers["timezone"],
            "tiers": {
                name: {
                    "daily_limit": row["daily_limit"],
                    "burst_limit_per_minute": row["burst_limit"],
                    "live_data": row["live_data"],
                    "description": row["description"],
                }
                for name, row in sorted(tiers["tiers"].items())
            },
            "documented_in": "docs/api-access.md",
        },
    }


def build_spec() -> dict[str, Any]:
    # Two real answers, merged: the example request (whose `managed_api` hosting
    # populates `applied.unbound`) and a fully constrained one (which binds every
    # filter and leaves `unbound` empty). Between them every field is seen.
    ranked = _answer(EXAMPLE_REQUEST)
    constrained = _answer({
        "use_case": "coding",
        "environment": {"hardware": "example_device", "hosting": "local", "runtime": "ollama"},
        "constraints": {"max_cost_per_million_input_tokens": 5.0, "price_sensitivity": 0.25,
                        "include_rehosts": True},
        "limit": 2,
    })
    errors = _probe_errors()
    entry_codes = entry_error_codes()

    used: set[str] = set()
    response_schema = _apply_vocabularies(
        _describe(_merge(_infer(ranked), _infer(constrained)), "RankResponse", used))
    row_schema = response_schema["properties"]["result"]["items"]
    response_schema["properties"]["result"]["items"] = _describe(row_schema, "RankedModel", used)

    no_match_schema = _apply_vocabularies(_describe(
        _merge(_infer(errors["no_match"][1]), _infer(errors["insufficient_evidence"][1]))
        ["properties"]["error"], "NoMatchError", used))
    no_match_schema["properties"]["code"]["enum"] = sorted(
        {errors[code][1]["error"]["code"] for code in ("no_match", "insufficient_evidence")})

    refused_codes = ("invalid_request", "unknown_use_case", "unknown_hardware",
                     "unknown_hosting", "unknown_runtime")
    refused: dict[str, Any] = {}
    for code in refused_codes:
        refused = _merge(refused, _infer(errors[code][1])["properties"]["error"])
    refused_schema = _describe(refused, "RequestRefusedError", used)
    refused_schema["properties"]["code"]["enum"] = sorted(
        {errors[code][1]["error"]["code"] for code in refused_codes})

    request_schema = _describe(_request_schema(), "RankRequest", used)
    health_schema = _infer(_health_sample())

    stray = sorted(set(DESCRIPTIONS) - used)
    if stray:
        raise SystemExit(
            "DESCRIPTIONS names field(s) the implementation no longer accepts or returns: "
            + ", ".join(stray))

    def error_envelope(schema: dict[str, Any]) -> dict[str, Any]:
        return {
            "type": "object",
            "required": ["schema_version", "error", "result"],
            "properties": {
                "schema_version": {"type": "string"},
                "service_commit": {"type": "string"},
                "error": schema,
                "result": {"type": "array", "items": {}, "maxItems": 0},
            },
        }

    codes = sorted(source_error_codes())
    return {
        "openapi": "3.0.3",
        "info": {
            "title": "ModelSpec rank API",
            "version": service.SCHEMA_VERSION,
            "summary": (
                "Ranks AI models you can actually run, given your hardware, providers, use "
                "case and policy rules."
            ),
            "description": (
                "Use when choosing, switching, or checking a model before a task or deploy. "
                "Returns ranked models with scores, cost and reasons; on failure, returns "
                "which constraint eliminated every option.\n\n"
                "One call, no state, no key today. The answer is computed per request from "
                "the current public export; `build.commit` on every response names the "
                "catalogue it was computed from. A request carries a profile — use case, "
                "environment, constraints — never a prompt.\n\n"
                "Send a real `User-Agent`. The host is behind Cloudflare, and the "
                "standard-library default (`Python-urllib/*`) is refused at the edge with a "
                "403 and a non-JSON body that never reaches this service.\n\n"
                "Reference: docs/api.md. Generated from the implementation by "
                "api/worker/openapi.py."
            ),
            "license": {"name": "MIT", "url": "https://github.com/turbobeest/modelspec"},
            "x-error-codes": codes,
            "x-transport-error-statuses": {code: entry_codes[code]
                                           for code in sorted(entry_codes)},
            "x-max-request-bytes": service.MAX_BODY_BYTES,
        },
        "x-modelspec-not-yet-live": _not_yet_live(),
        "servers": [{"url": SERVER_URL, "description": "production"}],
        "paths": {
            "/v1/health": {
                "get": {
                    "operationId": "health",
                    "summary": "The deployed version, and whether it can read the export.",
                    "responses": {
                        "200": _json_body("Serving.", {"$ref": "#/components/schemas/Health"}),
                        str(service.HTTP_BAD_GATEWAY): _json_body(
                            "The published export could not be read. `last_error` says why.",
                            {"$ref": "#/components/schemas/Health"}),
                        # Reachable from either operation: the router answers any
                        # unrecognised path this way, including a mistyped one.
                        str(service.HTTP_NOT_FOUND): _json_body(
                            "No endpoint at that path. `error.accepted` names the versioned "
                            "paths.", {"$ref": "#/components/schemas/TransportError"}),
                    },
                },
            },
            "/v1/rank": {
                "post": {
                    "operationId": "rank",
                    "summary": "Rank the catalogue for one profile.",
                    "requestBody": {
                        "required": True,
                        "content": {"application/json": {
                            "schema": {"$ref": "#/components/schemas/RankRequest"},
                            "example": EXAMPLE_REQUEST,
                        }},
                    },
                    "responses": {
                        "200": _json_body("A shortlist. `result` is never empty.",
                                          {"$ref": "#/components/schemas/RankResponse"}),
                        str(service.HTTP_BAD_REQUEST): _json_body(
                            "Refused. `error.accepted` lists the values this field takes.",
                            {"$ref": "#/components/schemas/RequestRefused"}),
                        str(service.HTTP_NOT_FOUND): _json_body(
                            "No endpoint at that path. `error.accepted` names the versioned "
                            "paths.", {"$ref": "#/components/schemas/TransportError"}),
                        str(service.HTTP_METHOD_NOT_ALLOWED): _json_body(
                            "/v1/rank takes POST.",
                            {"$ref": "#/components/schemas/TransportError"}),
                        str(service.HTTP_PAYLOAD_TOO_LARGE): _json_body(
                            f"The body is over {service.MAX_BODY_BYTES} bytes.",
                            {"$ref": "#/components/schemas/TransportError"}),
                        str(service.HTTP_NO_MATCH): _json_body(
                            "No model survives the request. `error.relax` names what to "
                            "change. Never a 200 with an empty list.",
                            {"$ref": "#/components/schemas/NoMatch"}),
                        str(service.HTTP_BAD_GATEWAY): _json_body(
                            "The published export could not be read. Retry.",
                            {"$ref": "#/components/schemas/TransportError"}),
                    },
                },
            },
        },
        "components": {
            "schemas": {
                "RankRequest": request_schema,
                "RankResponse": response_schema,
                "Health": health_schema,
                "NoMatch": error_envelope(no_match_schema),
                "RequestRefused": error_envelope(refused_schema),
                "TransportError": error_envelope({
                    "type": "object",
                    "required": ["code", "message"],
                    "properties": {
                        "code": {"type": "string",
                                 "enum": sorted(entry_codes) or ["not_found"]},
                        "message": {"type": "string"},
                        "accepted": {"type": "array", "items": {"type": "string"}},
                    },
                }),
            },
        },
    }


def _json_body(description: str, schema: dict[str, Any]) -> dict[str, Any]:
    return {"description": description, "content": {"application/json": {"schema": schema}}}


def _health_sample() -> dict[str, Any]:
    """`/v1/health`'s body, in the shape `entry.py::_health` writes it."""
    export = _export()
    build = export["build"]
    return {
        "schema_version": service.SCHEMA_VERSION,
        "endpoint": "health",
        "service_commit": _COMMIT,
        "export_origin": _ORIGIN,
        "export_loaded": True,
        "build": {"commit": build["commit"], "built_at": build["built_at"],
                  "export_schema_version": build["export_schema_version"]},
        "model_count": len(export["candidates"]),
        "last_error": None,
    }


def render() -> str:
    return HEADER + yaml.safe_dump(build_spec(), sort_keys=False, allow_unicode=True, width=100)


# ── the live proof ───────────────────────────────────────────────────────────

def _example_from_schema(schema: dict[str, Any], spec: dict[str, Any]) -> Any:
    """Build a value from the spec alone. No knowledge of the implementation."""
    while "$ref" in schema:
        node: Any = spec
        for part in schema["$ref"].lstrip("#/").split("/"):
            node = node[part]
        schema = node
    if "example" in schema:
        return schema["example"]
    if "enum" in schema:
        return schema["enum"][0]
    kind = schema.get("type")
    if kind == "object":
        return {name: _example_from_schema(schema["properties"][name], spec)
                for name in schema.get("required", [])}
    if kind == "integer":
        return int(schema.get("default", schema.get("minimum", 1)) or 1)
    if kind == "number":
        return float(schema.get("default", schema.get("minimum", 0)) or 0)
    if kind == "boolean":
        return bool(schema.get("default", False))
    if kind == "array":
        return []
    return schema.get("default", "")


def _validate(value: Any, schema: dict[str, Any], spec: dict[str, Any],
              path: str = "$") -> list[str]:
    """Check a response against the spec's schema. Enough of JSON Schema to bite."""
    while "$ref" in schema:
        node: Any = spec
        for part in schema["$ref"].lstrip("#/").split("/"):
            node = node[part]
        schema = node
    problems: list[str] = []
    if value is None:
        if not schema.get("nullable") and schema.get("type"):
            problems.append(f"{path}: null, but the spec says {schema['type']}")
        return problems
    kind = schema.get("type")
    checks = {
        "object": dict, "array": list, "string": str, "boolean": bool,
        "integer": int, "number": (int, float),
    }
    if kind in checks and not isinstance(value, checks[kind]):
        return [f"{path}: {type(value).__name__}, but the spec says {kind}"]
    if kind in {"integer", "number"} and isinstance(value, bool):
        return [f"{path}: boolean, but the spec says {kind}"]
    if "enum" in schema and value not in schema["enum"]:
        problems.append(f"{path}: {value!r} is not one of the spec's {len(schema['enum'])} values")
    if kind == "object":
        for name in schema.get("required", []):
            if name not in value:
                problems.append(f"{path}.{name}: required by the spec, absent from the response")
        for name, child in (schema.get("properties") or {}).items():
            if name in value:
                problems += _validate(value[name], child, spec, f"{path}.{name}")
    if kind == "array":
        if "maxItems" in schema and len(value) > schema["maxItems"]:
            problems.append(f"{path}: {len(value)} items, spec allows {schema['maxItems']}")
        for index, entry in enumerate(value[:3]):
            problems += _validate(entry, schema.get("items") or {}, spec, f"{path}[{index}]")
    return problems


def probe(base_url: str, spec: dict[str, Any] | None = None) -> int:
    """Send a request built from the spec alone, and check the answer against it.

    This is the acceptance criterion made executable: if a caller can only read
    `openapi.yaml`, can they call the service and parse what comes back.
    """
    spec = spec or yaml.safe_load(SPEC_PATH.read_text(encoding="utf-8"))
    base = base_url.rstrip("/")
    failures: list[str] = []

    for path, method in (("/v1/health", "get"), ("/v1/rank", "post")):
        operation = spec["paths"][path][method]
        data = None
        if method == "post":
            schema = operation["requestBody"]["content"]["application/json"]["schema"]
            body = _example_from_schema(
                operation["requestBody"]["content"]["application/json"].get("schema", schema), spec)
            example = operation["requestBody"]["content"]["application/json"].get("example")
            body = example if example is not None else body
            data = json.dumps(body).encode()
            print(f"POST {base}{path} {json.dumps(body)}")
        else:
            print(f"GET {base}{path}")
        headers = {"user-agent": USER_AGENT}
        if data:
            headers["content-type"] = "application/json"
        request = urllib.request.Request(base + path, data=data, method=method.upper(),
                                         headers=headers)
        try:
            with urllib.request.urlopen(request, timeout=60) as response:
                status, raw = response.status, response.read()
        except urllib.error.HTTPError as exc:  # documented statuses arrive here
            status, raw = exc.code, exc.read() or b""
        except OSError as exc:
            failures.append(f"{path}: {exc}")
            continue
        try:
            payload = json.loads(raw or b"{}")
        except ValueError:
            # Cloudflare's own refusals are not this service's envelope. 1010 is
            # the default-library user agent being blocked at the edge.
            failures.append(f"{path}: HTTP {status} with a non-JSON body "
                            f"({raw[:60]!r}) — that answer is not from the Worker")
            continue

        print(f"  -> HTTP {status}")
        if str(status) not in operation["responses"]:
            failures.append(f"{path}: HTTP {status} is not in the spec")
            continue
        if method == "post" and status != 200:
            failures.append(f"{path}: the spec's own example returned HTTP {status}, not 200")
        schema = operation["responses"][str(status)]["content"]["application/json"]["schema"]
        problems = _validate(payload, schema, spec, path)
        failures += [f"{path}: {problem}" for problem in problems]
        if method == "post" and status == 200:
            print(f"  -> {len(payload.get('result', []))} ranked row(s), "
                  f"build.commit={payload.get('build', {}).get('commit')}")

    for failure in failures:
        print(f"::error::{failure}")
    if failures:
        return 1
    print(f"a request built only from {SPEC_PATH.name} succeeds against {base}, "
          "and both answers validate against it")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed spec is not what this generates")
    parser.add_argument("--probe", metavar="BASE_URL",
                        help="call a live service using only the committed spec")
    args = parser.parse_args(argv)

    if args.probe:
        return probe(args.probe)

    text = render()
    if args.check:
        current = SPEC_PATH.read_text(encoding="utf-8") if SPEC_PATH.exists() else ""
        if current != text:
            print(f"::error::{SPEC_PATH.relative_to(REPO_ROOT)} is stale. The implementation "
                  "changed, or the file was edited by hand. Run `python "
                  "api/worker/openapi.py` and commit the result.")
            return 1
        print(f"{SPEC_PATH.relative_to(REPO_ROOT)} matches the implementation")
        return 0

    SPEC_PATH.write_text(text, encoding="utf-8")
    print(f"wrote {SPEC_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
