# Generated by pipeline.agent_copy; do not edit.
GUIDE_URL = 'https://modelspec.dev/agents.md'
GUIDE_VERSION = '1-ba4c092afcb11838'
MINIMAL_SPEC = {'spec_version': 1, 'optimize': {'min': 'offering.cost_per_task'}}
VOCAB_NEXT = {'starter': 'next: call decide with this; refine from reading', 'lookup': 'next: call decide using these ids; refine from reading'}
