import { McpServer } from "@modelcontextprotocol/server";
// MODEL-257: every description and the server instructions are generated by
// pipeline/agent_copy.py; edit that and run `python -m pipeline.agent_copy write`.
import agentCopy from "./agent-copy.json";
import { createMcpHandler } from "agents/mcp/server";
import { z } from "zod";

import { lookupVocabulary, vocabInput, vocabularyResponse } from "./vocabulary";

import decisionContract from "../../docs/decision-contract.schema.json";
import {
  asToolResult,
  fetchOrigin,
  incomingAuthorization,
  incomingClientAddress,
  modelCardUrl,
  type OriginEnvelope,
} from "./origin";

export const TOOL_NAMES = [
  "rank",
  "model_info",
  "list_use_cases",
  "policy_check",
  "decide",
  "vocab",
  "feedback",
] as const;


const rankInput = z
  .object({
    use_case: z
      .string()
      .describe("Ranking profile id, as published in /api/rank/profiles.json"),
    environment: z
      .object({
        hardware: z.string().nullable().optional(),
        hosting: z.enum(["local", "self_hosted", "managed_api"]).nullable().optional(),
        runtime: z.string().nullable().optional(),
      })
      .optional(),
    constraints: z
      .object({
        open_weights: z.boolean().nullable().optional(),
        max_cost_per_million_input_tokens: z.number().nullable().optional(),
        price_sensitivity: z.number().nullable().optional(),
        include_rehosts: z.boolean().nullable().optional(),
      })
      .optional(),
    limit: z.number().int().min(0).max(100).optional(),
  })
  .passthrough();

const policyInput = z
  .object({
    policy: z
      .object({
        name: z.string().optional(),
        licence: z
          .object({
            allowed: z.array(z.string()).optional(),
            prohibited: z.array(z.string()).optional(),
          })
          .optional(),
        origin: z
          .object({
            permitted_countries: z.array(z.string()).optional(),
            prohibited_countries: z.array(z.string()).optional(),
          })
          .optional(),
        residency: z
          .object({
            required_regions: z.array(z.string()).optional(),
            match: z.enum(["any", "all"]).optional(),
          })
          .optional(),
        commercial_use: z
          .object({
            required: z.boolean().optional(),
            accept_restricted: z.boolean().optional(),
          })
          .optional(),
      })
      .passthrough(),
    require_no_undetermined: z.boolean().optional(),
    models: z.array(z.string()).optional(),
    platforms: z.array(z.string()).optional(),
    verdicts: z.array(z.enum(["pass", "fail", "undetermined"])).optional(),
    limit: z.number().int().min(0).max(500).optional(),
    offset: z.number().int().min(0).optional(),
  })
  .passthrough();

/** MODEL-221. The same fields /v1/feedback accepts, minus `client`, which is always "mcp". */
const feedbackInput = z
  .object({
    rating: z
      .enum(["reliable", "unreliable", "trustworthy", "untrustworthy", "confusing"])
      .describe("How the answer held up when you acted on it."),
    decision_id: z
      .string()
      .regex(/^dec_[0-9A-Za-z]{8,64}$/)
      .optional()
      .describe("The decision_id of the answer this is about."),
    note: z
      .string()
      .max(1000)
      .optional()
      .describe("Optional. What was wrong or right. Never a prompt, a key or personal details."),
    trying_to_decide: z
      .string()
      .max(300)
      .optional()
      .describe("Optional. What you were trying to decide."),
    template: z
      .string()
      .regex(/^[a-z0-9][a-z0-9-]{0,63}$/)
      .optional()
      .describe("Optional. The decision template you used."),
  })
  .strict();

type JsonSchemaObject = Exclude<
  Parameters<typeof z.fromJSONSchema>[0],
  boolean
>;

const DECIDE_DEFAULTS = {
  explain: "none",
  limit: 10,
  fields: ["model_rank", "cost_per_task", "estimates", "p_best"],
};

/** Row fields the engine fills when explain is summary or full. Mirrors decision/bounded.py. */
const EXPLAIN_ROW_FIELDS = ["contributions", "evidence"] as const;

/** Compact UTF-8 budget for the MCP text: origin envelope plus decisionSummary. */
export const AGENT_BYTES = 16_384;

// Same arm as qa.contracts.CONDITION_UNION. A changed shape is refused, not served long.
const CONDITION_UNION = [
  { type: "string" },
  { $ref: "#/$defs/Compare" },
  { $ref: "#/$defs/Window" },
  { $ref: "#/$defs/InSet" },
  { $ref: "#/$defs/Known" },
  { $ref: "#/$defs/AnyOf" },
  { $ref: "#/$defs/AllOf" },
  { $ref: "#/$defs/NotOf" },
];
const CONDITION_DEF_REFS = new Set(
  CONDITION_UNION.flatMap((item) => ("$ref" in item ? [item.$ref] : [])),
);
const SCHEMA_MAPS = ["properties", "patternProperties", "$defs", "definitions", "dependentSchemas"];
const SCHEMA_NODES = [
  "items", "additionalProperties", "unevaluatedProperties", "unevaluatedItems",
  "contains", "not", "if", "then", "else", "propertyNames", "additionalItems",
];
const SCHEMA_ARRAYS = ["anyOf", "oneOf", "allOf", "prefixItems"];

function isSchemaRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function jsonEqual(left: unknown, right: unknown): boolean {
  if (Object.is(left, right)) return true;
  if (Array.isArray(left) || Array.isArray(right)) {
    if (!Array.isArray(left) || !Array.isArray(right) || left.length !== right.length) return false;
    return left.every((item, index) => jsonEqual(item, right[index]));
  }
  if (!isSchemaRecord(left) || !isSchemaRecord(right)) return false;
  const keys = Object.keys(left);
  if (keys.length !== Object.keys(right).length) return false;
  return keys.every((key) => Object.hasOwn(right, key) && jsonEqual(left[key], right[key]));
}

function citesCondition(value: unknown[]): boolean {
  return value.some((item) => (
    isSchemaRecord(item) && typeof item.$ref === "string" && CONDITION_DEF_REFS.has(item.$ref)
  ));
}

function replaceKey(node: Record<string, unknown>, oldKey: string, newKey: string, value: unknown): void {
  const rebuilt: Record<string, unknown> = {};
  for (const [key, child] of Object.entries(node)) {
    rebuilt[key === oldKey ? newKey : key] = key === oldKey ? value : child;
  }
  for (const key of Object.keys(node)) delete node[key];
  Object.assign(node, rebuilt);
}

function compactInPlace(node: unknown): number {
  // `title` inside properties or patternProperties is a field name, not the keyword.
  if (Array.isArray(node)) return node.reduce((found, item) => found + compactInPlace(item), 0);
  if (!isSchemaRecord(node)) return 0;
  let found = 0;
  for (const key of SCHEMA_MAPS) {
    const child = node[key];
    if (!isSchemaRecord(child)) continue;
    for (const sub of Object.values(child)) found += compactInPlace(sub);
  }
  for (const key of SCHEMA_NODES) {
    if (key in node) found += compactInPlace(node[key]);
  }
  for (const key of SCHEMA_ARRAYS) {
    const value = node[key];
    if (!Array.isArray(value)) continue;
    if (key === "anyOf" && jsonEqual(value, CONDITION_UNION)) {
      replaceKey(node, "anyOf", "$ref", "#/$defs/Condition");
      found += 1;
      continue;
    }
    if (citesCondition(value)) {
      throw new Error(
        "decision condition union changed; refusing to serve the uncompacted decide schema",
      );
    }
    for (const item of value) found += compactInPlace(item);
  }
  if ("title" in node) delete node.title;
  if ("default" in node && node.default === null) delete node.default;
  return found;
}

function addCondition(schema: unknown): void {
  if (!isSchemaRecord(schema) || !isSchemaRecord(schema.$defs)) {
    throw new Error("hoisted condition union but the decide schema has no $defs");
  }
  schema.$defs.Condition = { anyOf: structuredClone(CONDITION_UNION) };
}

/** Drop null defaults and titles, and alias the repeated condition union. */
export function compactDecideSchema<T>(schema: T): T {
  const compacted = structuredClone(schema);
  if (compactInPlace(compacted) > 0) addCondition(compacted);
  return compacted;
}

function decisionSpecJsonSchema(): JsonSchemaObject {
  if (
    decisionContract.$schema !== "https://json-schema.org/draft/2020-12/schema" ||
    !("DecideRequest" in decisionContract.$defs)
  ) {
    throw new Error("decision-contract.schema.json has no decision Spec definition");
  }
  const available = new Map(Object.entries(decisionContract.$defs));
  const definitions: Record<string, (typeof decisionContract.$defs)[keyof typeof decisionContract.$defs]> = {};
  const pending = ["DecideRequest"];
  while (pending.length) {
    const name = pending.pop();
    if (name === undefined || name in definitions) continue;
    const definition = available.get(name);
    if (definition === undefined) throw new Error(`Missing decision definition ${name}`);
    definitions[name] = definition;
    for (const match of JSON.stringify(definition).matchAll(/#\/\$defs\/([^" ]+)/g)) {
      pending.push(match[1]);
    }
  }
  const schema = {
    $schema: decisionContract.$schema,
    $defs: {
      ...definitions,
      DecideRequest: {
        ...decisionContract.$defs.DecideRequest,
        properties: {
          ...decisionContract.$defs.DecideRequest.properties,
          explain: { ...decisionContract.$defs.DecideRequest.properties.explain, default: DECIDE_DEFAULTS.explain },
          limit: { ...decisionContract.$defs.DecideRequest.properties.limit, default: DECIDE_DEFAULTS.limit },
          fields: { ...decisionContract.$defs.DecideRequest.properties.fields, default: DECIDE_DEFAULTS.fields },
        },
      },
    },
    $ref: "#/$defs/DecideRequest",
  };
  return compactDecideSchema(schema) as JsonSchemaObject;
}

const decisionSpecSchema = decisionSpecJsonSchema();
const decisionSpecInput = {
  "~standard": {
    version: 1 as const,
    vendor: "modelspec",
    validate(value: unknown) {
      // The Worker validates structure and facets together and returns recovery examples.
      return { value };
    },
    jsonSchema: {
      input: () => decisionSpecSchema,
      output: () => decisionSpecSchema,
    },
  },
};



type DecisionBody = {
  status?: unknown;
  answer?: unknown;
  results?: unknown;
  may_qualify?: unknown;
  model_evidence?: unknown;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function answerSummary(answer: unknown): string {
  if (!isRecord(answer) || !Array.isArray(answer.members)) return "answer: none";
  const members = answer.members.filter((m): m is string => typeof m === "string");
  // Bounded like the top-models list; the body's answer.members stays complete.
  const shown = members.slice(0, 5).join(", ");
  const more = members.length > 5 ? ` and ${members.length - 5} more in answer.members` : "";
  if (answer.kind === "tied") return `answer: tied among ${shown}${more}`;
  return `answer: ${shown || "none"}`;
}

export function decisionSummary(body: unknown): string {
  const decision: DecisionBody = isRecord(body) ? body : {};
  const status = typeof decision.status === "string" ? decision.status : "unknown";
  // A drill-down carries no result or may_qualify rows by design: summarise the
  // answer and the one model it explains, never "top models: none".
  if (isRecord(decision.model_evidence)) {
    const detail = decision.model_evidence;
    const model = typeof detail.model === "string" ? detail.model : "unknown";
    const modelStatus = typeof detail.status === "string" ? detail.status : "unknown";
    const rank = typeof detail.rank === "number" ? `rank ${detail.rank}` : "unranked";
    return (
      `status: ${status}; ${answerSummary(decision.answer)}; ` +
      `evidence for: ${model} (${modelStatus}, ${rank})`
    );
  }
  const results = Array.isArray(decision.results) ? decision.results : [];
  const models = results
    .flatMap((result) => {
      if (!isRecord(result) || !isRecord(result.offering)) return [];
      const model = result.offering.model;
      return typeof model === "string" ? [model] : [];
    })
    .filter((model, index, all) => all.indexOf(model) === index)
    .slice(0, 5);
  const mayQualify = Array.isArray(decision.may_qualify)
    ? decision.may_qualify.length
    : 0;
  return (
    `status: ${status}; top models: ${models.length ? models.join(", ") : "none"}; ` +
    `may qualify: ${mayQualify}`
  );
}

/**
 * The MCP default path always requests the bounded representation.
 * explain "summary" or "full" keeps explanation-bearing row fields.
 * A caller who passes `fields`, including null, overrides that list.
 */
export function defaultDecideRequest(spec: unknown): unknown {
  if (!isRecord(spec)) return spec;
  const explained = spec.explain === "summary" || spec.explain === "full";
  const fields =
    "fields" in spec
      ? spec.fields
      : explained
        ? [...DECIDE_DEFAULTS.fields, ...EXPLAIN_ROW_FIELDS]
        : [...DECIDE_DEFAULTS.fields];
  return {
    ...DECIDE_DEFAULTS,
    ...spec,
    fields,
  };
}

function utf8Bytes(text: string): number {
  return new TextEncoder().encode(text).length;
}

function envelopeBytes(envelope: OriginEnvelope): number {
  const packed = utf8Bytes(JSON.stringify(envelope));
  const summarised = envelope.status !== 0 && envelope.status < 400;
  return packed + (summarised ? utf8Bytes(decisionSummary(envelope.body)) : 0);
}

function offeringModel(row: Record<string, unknown>): string | undefined {
  if (isRecord(row.offering) && typeof row.offering.model === "string") return row.offering.model;
  return typeof row.model === "string" ? row.model : undefined;
}

function slimOffering(row: Record<string, unknown>): Record<string, unknown> | undefined {
  if (!isRecord(row.offering) || typeof row.offering.model !== "string") return undefined;
  const offering: Record<string, unknown> = { model: row.offering.model };
  for (const key of ["provider", "region", "tier"]) {
    const value = row.offering[key];
    if (typeof value === "string") offering[key] = value;
  }
  return offering;
}

function fetchPointer(model: string | undefined): string {
  const drill = model ? `evidence_for: ${model}` : "evidence_for: <model>";
  return (
    "explanation.omitted counts records removed from this bounded answer. " +
    `Resend this spec with ${drill} for one model's evidence; ` +
    "narrow fields or lower limit; " +
    "or POST /v1/decide without fields for the complete Decision."
  );
}

function listCount(value: unknown): number {
  return Array.isArray(value) ? value.length : 0;
}

function addCount(omitted: Record<string, unknown>, key: string, count: number) {
  if (count <= 0) return;
  const prior = omitted[key];
  omitted[key] = (typeof prior === "number" && Number.isFinite(prior) ? prior : 0) + count;
}

/**
 * Last-resort notice when a caller asked for a body the Worker did not bound
 * (for example fields: null). Keeps the answer, status, warnings, coverage,
 * summary_for_user, must_mention and one slim top result. Does not call the
 * Worker again.
 */
function slimDecision(body: Record<string, unknown>): Record<string, unknown> {
  const results = Array.isArray(body.results) ? body.results.filter(isRecord) : [];
  const first = results[0];
  const members =
    isRecord(body.answer) && Array.isArray(body.answer.members)
      ? body.answer.members.filter((model): model is string => typeof model === "string")
      : [];
  const detail = isRecord(body.model_evidence) ? body.model_evidence : undefined;
  const model =
    (detail && typeof detail.model === "string" ? detail.model : undefined) ??
    (first ? offeringModel(first) : undefined) ??
    members[0];
  const omitted: Record<string, unknown> = {};
  if (isRecord(body.explanation) && isRecord(body.explanation.omitted)) {
    for (const [key, value] of Object.entries(body.explanation.omitted)) {
      if (typeof value === "number" && Number.isFinite(value)) addCount(omitted, key, value);
    }
  }
  addCount(omitted, "results", results.length - (first ? 1 : 0));
  addCount(omitted, "may_qualify", listCount(body.may_qualify));
  for (const key of ["by_model", "blend", "top", "near_misses", "number_origins", "sources", "constraint_costs", "tipping_points"]) {
    addCount(omitted, key, listCount(body[key]));
  }
  if (isRecord(body.bands)) {
    addCount(
      omitted,
      "bands",
      ["best", "rest", "thin"].reduce(
        (sum, key) => sum + listCount(isRecord(body.bands) ? body.bands[key] : undefined),
        0,
      ),
    );
  }
  if (isRecord(body.eliminated)) {
    for (const key of ["models", "model_groups", "funnel"]) {
      addCount(omitted, `eliminated.${key}`, listCount(body.eliminated[key]));
    }
  }
  if (first) {
    for (const key of ["evidence", "contributions", "estimates", "refinement_estimates", "plans"]) {
      addCount(omitted, `results.${key}`, listCount(first[key]));
    }
  }
  const notice: Record<string, unknown> = {};
  if (body.representation === "bounded" || typeof body.contract_version === "string" || typeof body.projects_contract === "string") {
    notice.representation = "bounded";
    notice.bounded_version = "1.1";
    notice.projects_contract =
      typeof body.projects_contract === "string"
        ? body.projects_contract
        : typeof body.contract_version === "string"
          ? body.contract_version
          : "2.15";
  }
  for (const key of [
    "decision_id", "snapshot", "signature_verified", "spec_hash", "explain", "status",
    "answer", "warnings", "truncated", "out_of_lineup", "relax", "relax_to", "relax_single", "feedback",
    "reading", "coverage", "summary_for_user", "must_mention", "member_evidence",
  ]) {
    if (key in body) notice[key] = body[key];
  }
  if (first) {
    const row: Record<string, unknown> = {};
    if (typeof first.rank === "number") row.rank = first.rank;
    if (typeof first.model === "string") row.model = first.model;
    const offering = slimOffering(first);
    if (offering) row.offering = offering;
    row.warnings = Array.isArray(first.warnings) ? first.warnings : [];
    notice.results = [row];
  } else {
    notice.results = [];
  }
  notice.may_qualify = [];
  if (detail) {
    const evidenceGroups = listCount(detail.evidence);
    const contributions = listCount(detail.contributions);
    if (evidenceGroups) omitted["model_evidence.evidence"] = evidenceGroups;
    if (contributions) omitted["model_evidence.contributions"] = contributions;
    notice.model_evidence = {
      model: detail.model,
      status: detail.status,
      offering: isRecord(detail.offering) ? slimOffering({ offering: detail.offering }) ?? detail.offering : detail.offering,
      rank: typeof detail.rank === "number" ? detail.rank : null,
      evidence: [],
      contributions: [],
      unknown: [],
      reasons: [],
      warnings: Array.isArray(detail.warnings) ? detail.warnings : [],
    };
  }
  if (Object.keys(omitted).length === 0) omitted.trimmed = 1;
  const priorNotApplied =
    isRecord(body.explanation) && Array.isArray(body.explanation.not_applied)
      ? body.explanation.not_applied
      : [];
  notice.explanation = {
    not_applied: priorNotApplied,
    omitted,
    note: "Projected rows are incomplete; omissions are not eliminations or absent evidence.",
    fetch: fetchPointer(model),
  };
  return notice;
}

function slimError(body: unknown): Record<string, unknown> {
  const error = isRecord(body) && isRecord(body.error) ? body.error : undefined;
  const code = error && typeof error.code === "string" ? error.code : "trimmed";
  const message = error && typeof error.message === "string"
    ? error.message
    : "The response exceeded 16 KB.";
  return {
    error: {
      code,
      message,
      fetch: "Retry with a narrower spec, or POST /v1/decide without fields for the complete Decision.",
    },
  };
}

function withinBudget(envelope: OriginEnvelope): boolean {
  return envelopeBytes(envelope) <= AGENT_BYTES;
}

function trimmedError(): Record<string, unknown> {
  return {
    error: {
      code: "trimmed",
      message: "The response exceeded 16 KB. Retry with a narrower spec.",
      fetch: "Retry with a narrower spec, or POST /v1/decide without fields for the complete Decision.",
    },
  };
}

function noticeOmitted(body: Record<string, unknown>): Record<string, unknown> {
  if (isRecord(body.explanation) && isRecord(body.explanation.omitted)) return body.explanation.omitted;
  return {};
}

function shortText(value: unknown, fallback: string, max = 80): string {
  return typeof value === "string" && value.length > 0 && value.length <= max ? value : fallback;
}

/**
 * Replace an over-budget decide body. Under-budget bodies pass through.
 * The returned text stays within AGENT_BYTES and keeps status, answer,
 * summary_for_user, must_mention and fetch.
 */
export function fitDecideEnvelope(envelope: OriginEnvelope): OriginEnvelope {
  if (withinBudget(envelope)) return envelope;
  if (!isRecord(envelope.body) || "error" in envelope.body) {
    const next = { ...envelope, body: slimError(envelope.body) };
    if (withinBudget(next)) return next;
    return { ...envelope, body: trimmedError() };
  }
  const bare = slimDecision(envelope.body);
  const fitted = { ...envelope, body: bare };
  if (withinBudget(fitted)) return fitted;
  const omitted = noticeOmitted(bare);
  for (const key of ["reading", "feedback", "relax", "relax_to", "relax_task_tokens", "relax_single", "with_estate"]) {
    if (withinBudget({ ...envelope, body: bare })) break;
    if (!(key in bare)) continue;
    addCount(omitted, key, 1);
    delete bare[key];
  }
  if (!withinBudget({ ...envelope, body: bare }) && Array.isArray(bare.warnings) && bare.warnings.length > 0) {
    addCount(omitted, "warnings", bare.warnings.length);
    bare.warnings = [];
  }
  if (!withinBudget({ ...envelope, body: bare }) && "coverage" in bare) {
    addCount(omitted, "coverage", 1);
    delete bare.coverage;
  }
  if (!withinBudget({ ...envelope, body: bare }) && "model_evidence" in bare) {
    addCount(omitted, "model_evidence", 1);
    delete bare.model_evidence;
  }
  // Drop member evidence before shortening the answer. A popped member must
  // not leave its records behind, and the evidence list is what usually
  // makes this notice too large.
  if (!withinBudget({ ...envelope, body: bare }) && "member_evidence" in bare) {
    const evidence = bare.member_evidence;
    const count = Array.isArray(evidence) ? evidence.length : 1;
    addCount(omitted, "member_evidence", count);
    delete bare.member_evidence;
  }
  if (isRecord(bare.answer) && Array.isArray(bare.answer.members)) {
    const members = bare.answer.members.filter((model): model is string => typeof model === "string");
    bare.answer = { ...bare.answer, members };
    while (members.length > 0 && !withinBudget({ ...envelope, body: bare })) {
      members.pop();
      addCount(omitted, "answer.members", 1);
    }
  }
  if (withinBudget({ ...envelope, body: bare })) return { ...envelope, body: bare };
  const priorTrimmed = omitted.trimmed;
  const minimal: Record<string, unknown> = {
    representation: "bounded",
    bounded_version: "1.1",
    projects_contract: shortText(bare.projects_contract, shortText(bare.contract_version, "2.15"), 16),
    status: shortText(bare.status, "trimmed"),
    answer: { kind: "tied", members: [] },
    warnings: [],
    results: [],
    may_qualify: [],
    explanation: {
      not_applied: [],
      omitted: { ...omitted, trimmed: (typeof priorTrimmed === "number" ? priorTrimmed : 0) + 1 },
      note: "Projected rows are incomplete; omissions are not eliminations or absent evidence.",
      fetch: fetchPointer(undefined),
    },
  };
  if (typeof bare.summary_for_user === "string") {
    minimal.summary_for_user = bare.summary_for_user;
  }
  if (Array.isArray(bare.must_mention)) {
    minimal.must_mention = bare.must_mention.filter((item): item is string => typeof item === "string");
  }
  const last = { ...envelope, body: minimal };
  return withinBudget(last) ? last : { ...envelope, body: trimmedError() };
}

export type McpFactoryContext = {
  requestInfo?: Request;
};

function jsonBody(value: unknown): string {
  return JSON.stringify(value);
}

function postInit(
  body: unknown,
  authorization: string | undefined,
): RequestInit {
  const headers = new Headers({ "content-type": "application/json" });
  if (authorization) headers.set("authorization", authorization);
  return { method: "POST", headers, body: jsonBody(body) };
}

export function createModelspecServer(env: Env, mcpCtx: McpFactoryContext = {}) {
  const authorization = incomingAuthorization(mcpCtx.requestInfo);
  function missingKey(origin: string) {
    if (env.MCP_REQUIRE_API_KEY === "false" || /^Bearer +\S+$/i.test(authorization ?? "")) return null;
    return {
      origin,
      status: 401,
      body: {
        error: {
          code: "missing_api_key",
          message: "MCP data tools require an API key. Send Authorization: Bearer <key>. " +
            "Get one at https://modelspec.dev/pricing/.",
          how_to_get_a_key: "https://modelspec.dev/pricing",
          docs: "https://modelspec.dev/docs/api",
        },
        result: [],
      },
    };
  }
  async function fetchDisplayVocabulary(query = "") {
    const origin = `${env.RANK_API_ORIGIN.replace(/\/$/, "")}/v1/vocabulary${query}`;
    const refusal = missingKey(origin);
    if (refusal) return refusal;
    const headers = new Headers();
    if (authorization) headers.set("authorization", authorization);
    const address = incomingClientAddress(mcpCtx.requestInfo);
    if (address) headers.set("CF-Connecting-IP", address);
    return fetchOrigin(origin, { headers }, env.RANK);
  }
  async function fetchDecision(origin: string, body: unknown) {
    const refusal = missingKey(origin);
    if (refusal) return refusal;
    return fetchOrigin(origin, postInit(body, authorization), env.RANK);
  }

  const server = new McpServer(
    { name: "modelspec", version: env.BUILD_COMMIT },
    { instructions: agentCopy.instructions },
  );

  server.registerTool(
    "rank",
    {
      description: agentCopy.tools.rank,
      inputSchema: rankInput,
    },
    async (args) => {
      const origin = `${env.RANK_API_ORIGIN.replace(/\/$/, "")}/v1/rank`;
      return asToolResult(await fetchDecision(origin, args));
    },
  );

  server.registerTool(
    "model_info",
    {
      description: agentCopy.tools.model_info,
      inputSchema: z.object({
        model_id: z.string().describe("Catalogue id, e.g. openai/gpt-5-6"),
      }),
    },
    async ({ model_id }) => {
      const located = modelCardUrl(env.EXPORT_ORIGIN, model_id);
      if ("error" in located) {
        return {
          content: [{ type: "text", text: located.error }],
          isError: true,
        };
      }
      if (env.DATA_SPLIT_ENABLED === "true") {
        const origin = `${env.RANK_API_ORIGIN.replace(/\/$/, "")}/v1/vocabulary`;
        const envelope = await fetchDisplayVocabulary();
        if (envelope.status < 400 && isRecord(envelope.body) && isRecord(envelope.body.models)) {
          envelope.body = envelope.body.models[model_id] ?? null;
        }
        return asToolResult(envelope);
      }
      const refusal = missingKey(located.origin);
      if (refusal) return asToolResult(refusal);
      return asToolResult(await fetchOrigin(located.origin));
    },
  );

  server.registerTool(
    "list_use_cases",
    {
      description: agentCopy.tools.list_use_cases,
      inputSchema: z.object({}),
    },
    async () => {
      const origin = `${env.EXPORT_ORIGIN.replace(/\/$/, "")}/api/rank/profiles.json`;
      const refusal = missingKey(origin);
      if (refusal) return asToolResult(refusal);
      return asToolResult(await fetchOrigin(origin));
    },
  );

  server.registerTool(
    "policy_check",
    {
      description: agentCopy.tools.policy_check,
      inputSchema: policyInput,
    },
    async (args) => {
      const origin = `${env.RANK_API_ORIGIN.replace(/\/$/, "")}/v1/policy-check`;
      return asToolResult(await fetchDecision(origin, args));
    },
  );

  server.registerTool(
    "decide",
    {
      description: agentCopy.tools.decide,
      inputSchema: decisionSpecInput,
    },
    async (spec) => {
      const origin = `${env.RANK_API_ORIGIN.replace(/\/$/, "")}/v1/decide`;
      const envelope = fitDecideEnvelope(await fetchDecision(origin, defaultDecideRequest(spec)));
      const result = asToolResult(envelope);
      if (result.isError) return result;
      return {
        ...result,
        content: [
          ...result.content,
          { type: "text" as const, text: decisionSummary(envelope.body) },
        ],
      };
    },
  );

  server.registerTool(
    "vocab",
    {
      description: agentCopy.tools.vocab,
      inputSchema: vocabInput,
    },
    async (args) => {
      const section = args.section ?? "starter";
      const split = env.DATA_SPLIT_ENABLED === "true";
      const query = new URLSearchParams({ section, detail: args.detail ?? "compact" });
      if (args.search !== undefined) query.set("search", args.search);
      if (args.id !== undefined) query.append("id", args.id);
      for (const id of args.ids ?? []) query.append("ids", id);
      if (args.offset !== undefined) query.set("offset", String(args.offset));
      if (args.limit !== undefined) query.set("limit", String(args.limit));
      const origin = `${env.EXPORT_ORIGIN.replace(/\/$/, "")}/api/decision/vocabulary.json`;
      if (!split) {
        const refusal = missingKey(origin);
        if (refusal) return asToolResult(refusal);
      }
      const envelope = split ? await fetchDisplayVocabulary(`?${query}`) : await fetchOrigin(origin);
      if (envelope.status < 400 && isRecord(envelope.body)) {
        // Older Workers ignore lookup parameters and return the full vocabulary.
        // Keep agent responses compact while the two Workers roll out independently.
        const selected = split && !("vocabulary_version" in envelope.body)
          ? envelope.body
          : lookupVocabulary(envelope.body, args);
        // Only a search or id lookup carries the cross-section keys; a plain lookup keeps its old body.
        envelope.body = "matches" in selected
          ? vocabularyResponse(selected[section], args, { facets: [], domains: [], templates: [], models: {}, estate: {}, ...selected })
          : vocabularyResponse(selected[section], args);
      }
      const result = asToolResult(envelope);
      // A failed lookup gets no "call decide next" hint: the agent should fix the lookup first.
      if (result.isError) return result;
      return {
        ...result,
        content: [...result.content, { type: "text" as const, text:
          isRecord(envelope.body) && typeof envelope.body.next === "string" ? envelope.body.next
            : section === "starter" ? agentCopy.vocab.next.starter : agentCopy.vocab.next.lookup }],
      };
    },
  );

  server.registerTool(
    "feedback",
    {
      description: agentCopy.tools.feedback,
      inputSchema: feedbackInput,
    },
    async (args) => {
      const origin = `${env.RANK_API_ORIGIN.replace(/\/$/, "")}/v1/feedback`;
      const headers = new Headers({ "content-type": "application/json" });
      // The rank Worker limits feedback per caller. Through the service binding
      // it sees no caller address of its own, so this one is forwarded. It is
      // an HMAC input there and is never stored.
      const address = incomingClientAddress(mcpCtx.requestInfo);
      if (address) headers.set("x-modelspec-client-ip", address);
      return asToolResult(
        await fetchOrigin(
          origin,
          { method: "POST", headers, body: jsonBody({ ...args, client: "mcp" }) },
          env.RANK,
        ),
      );
    },
  );

  return server;
}

export function handlerOptions() {
  return {
    route: "/mcp",
    allowedHostnames: ["api.modelspec.dev", "localhost", "127.0.0.1"],
    allowedOriginHostnames: ["localhost", "127.0.0.1"],
  };
}

export function mcpHandler(env: Env) {
  return createMcpHandler(
    (ctx) => createModelspecServer(env, ctx),
    handlerOptions(),
  );
}
