import { McpServer } from "@modelcontextprotocol/server";
// MODEL-257: every description and the server instructions are generated by
// pipeline/agent_copy.py; edit that and run `python -m pipeline.agent_copy write`.
import agentCopy from "./agent-copy.json";
import { createMcpHandler } from "agents/mcp/server";
import { z } from "zod";

import { lookupVocabulary, vocabInput } from "./vocabulary";

import decisionContract from "../../docs/decision-contract.schema.json";
import {
  asToolResult,
  fetchOrigin,
  incomingAuthorization,
  incomingClientAddress,
  modelCardUrl,
} from "./origin";

export const TOOL_NAMES = [
  "rank",
  "model_info",
  "list_use_cases",
  "policy_check",
  "decide",
  "vocab",
  "feedback",
] as const;


const rankInput = z
  .object({
    use_case: z
      .string()
      .describe("Ranking profile id, as published in /api/rank/profiles.json"),
    environment: z
      .object({
        hardware: z.string().nullable().optional(),
        hosting: z.enum(["local", "self_hosted", "managed_api"]).nullable().optional(),
        runtime: z.string().nullable().optional(),
      })
      .optional(),
    constraints: z
      .object({
        open_weights: z.boolean().nullable().optional(),
        max_cost_per_million_input_tokens: z.number().nullable().optional(),
        price_sensitivity: z.number().nullable().optional(),
        include_rehosts: z.boolean().nullable().optional(),
      })
      .optional(),
    limit: z.number().int().min(0).max(100).optional(),
  })
  .passthrough();

const policyInput = z
  .object({
    policy: z
      .object({
        name: z.string().optional(),
        licence: z
          .object({
            allowed: z.array(z.string()).optional(),
            prohibited: z.array(z.string()).optional(),
          })
          .optional(),
        origin: z
          .object({
            permitted_countries: z.array(z.string()).optional(),
            prohibited_countries: z.array(z.string()).optional(),
          })
          .optional(),
        residency: z
          .object({
            required_regions: z.array(z.string()).optional(),
            match: z.enum(["any", "all"]).optional(),
          })
          .optional(),
        commercial_use: z
          .object({
            required: z.boolean().optional(),
            accept_restricted: z.boolean().optional(),
          })
          .optional(),
      })
      .passthrough(),
    require_no_undetermined: z.boolean().optional(),
    models: z.array(z.string()).optional(),
    platforms: z.array(z.string()).optional(),
    verdicts: z.array(z.enum(["pass", "fail", "undetermined"])).optional(),
    limit: z.number().int().min(0).max(500).optional(),
    offset: z.number().int().min(0).optional(),
  })
  .passthrough();

/** MODEL-221. The same fields /v1/feedback accepts, minus `client`, which is always "mcp". */
const feedbackInput = z
  .object({
    rating: z
      .enum(["reliable", "unreliable", "trustworthy", "untrustworthy", "confusing"])
      .describe("How the answer held up when you acted on it."),
    decision_id: z
      .string()
      .regex(/^dec_[0-9A-Za-z]{8,64}$/)
      .optional()
      .describe("The decision_id of the answer this is about."),
    note: z
      .string()
      .max(1000)
      .optional()
      .describe("Optional. What was wrong or right. Never a prompt, a key or personal details."),
    trying_to_decide: z
      .string()
      .max(300)
      .optional()
      .describe("Optional. What you were trying to decide."),
    template: z
      .string()
      .regex(/^[a-z0-9][a-z0-9-]{0,63}$/)
      .optional()
      .describe("Optional. The decision template you used."),
  })
  .strict();

type JsonSchemaObject = Exclude<
  Parameters<typeof z.fromJSONSchema>[0],
  boolean
>;

function decisionSpecJsonSchema(): JsonSchemaObject {
  if (
    decisionContract.$schema !== "https://json-schema.org/draft/2020-12/schema" ||
    !("Spec" in decisionContract.$defs)
  ) {
    throw new Error("decision-contract.schema.json has no decision Spec definition");
  }
  const available = new Map(Object.entries(decisionContract.$defs));
  const definitions: Record<string, (typeof decisionContract.$defs)[keyof typeof decisionContract.$defs]> = {};
  const pending = ["Spec"];
  while (pending.length) {
    const name = pending.pop();
    if (name === undefined || name in definitions) continue;
    const definition = available.get(name);
    if (definition === undefined) throw new Error(`Missing decision definition ${name}`);
    definitions[name] = definition;
    for (const match of JSON.stringify(definition).matchAll(/#\/\$defs\/([^" ]+)/g)) {
      pending.push(match[1]);
    }
  }
  return {
    $schema: decisionContract.$schema,
    $defs: definitions,
    $ref: "#/$defs/Spec",
  } as JsonSchemaObject;
}

const decisionSpecSchema = decisionSpecJsonSchema();
const decisionSpecInput = {
  "~standard": {
    version: 1 as const,
    vendor: "modelspec",
    validate(value: unknown) {
      // The Worker validates structure and facets together and returns recovery examples.
      return { value };
    },
    jsonSchema: {
      input: () => decisionSpecSchema,
      output: () => decisionSpecSchema,
    },
  },
};



type DecisionBody = {
  status?: unknown;
  results?: unknown;
  may_qualify?: unknown;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function decisionSummary(body: unknown): string {
  const decision: DecisionBody = isRecord(body) ? body : {};
  const status = typeof decision.status === "string" ? decision.status : "unknown";
  const results = Array.isArray(decision.results) ? decision.results : [];
  const models = results
    .flatMap((result) => {
      if (!isRecord(result) || !isRecord(result.offering)) return [];
      const model = result.offering.model;
      return typeof model === "string" ? [model] : [];
    })
    .filter((model, index, all) => all.indexOf(model) === index)
    .slice(0, 5);
  const mayQualify = Array.isArray(decision.may_qualify)
    ? decision.may_qualify.length
    : 0;
  return (
    `status: ${status}; top models: ${models.length ? models.join(", ") : "none"}; ` +
    `may qualify: ${mayQualify}`
  );
}

export type McpFactoryContext = {
  requestInfo?: Request;
};

function jsonBody(value: unknown): string {
  return JSON.stringify(value);
}

function postInit(
  body: unknown,
  authorization: string | undefined,
): RequestInit {
  const headers = new Headers({ "content-type": "application/json" });
  if (authorization) headers.set("authorization", authorization);
  return { method: "POST", headers, body: jsonBody(body) };
}

export function createModelspecServer(env: Env, mcpCtx: McpFactoryContext = {}) {
  const authorization = incomingAuthorization(mcpCtx.requestInfo);
  async function fetchDisplayVocabulary(query = "") {
    const headers = new Headers();
    const address = incomingClientAddress(mcpCtx.requestInfo);
    if (address) headers.set("CF-Connecting-IP", address);
    const origin = `${env.RANK_API_ORIGIN.replace(/\/$/, "")}/v1/vocabulary${query}`;
    return fetchOrigin(origin, { headers }, env.RANK);
  }
  async function fetchDecision(origin: string, body: unknown) {
    // The API permits anonymous answers while ACCESS_ENFORCED is off.
    // Require credentials here before that request can reach its anonymous path.
    if (
      env.MCP_REQUIRE_API_KEY !== "false" &&
      !/^Bearer +\S+$/i.test(authorization ?? "")
    ) {
      return {
        origin,
        status: 401,
        body: {
          error: {
            code: "missing_api_key",
            message:
              "MCP decisions require an API key. Send Authorization: Bearer <key>. " +
              "Get one at https://modelspec.dev/pricing/.",
          },
          result: [],
        },
      };
    }
    return fetchOrigin(origin, postInit(body, authorization), env.RANK);
  }

  const server = new McpServer(
    { name: "modelspec", version: env.BUILD_COMMIT },
    { instructions: agentCopy.instructions },
  );

  server.registerTool(
    "rank",
    {
      description: agentCopy.tools.rank,
      inputSchema: rankInput,
    },
    async (args) => {
      const origin = `${env.RANK_API_ORIGIN.replace(/\/$/, "")}/v1/rank`;
      return asToolResult(await fetchDecision(origin, args));
    },
  );

  server.registerTool(
    "model_info",
    {
      description: agentCopy.tools.model_info,
      inputSchema: z.object({
        model_id: z.string().describe("Catalogue id, e.g. openai/gpt-5-6"),
      }),
    },
    async ({ model_id }) => {
      const located = modelCardUrl(env.EXPORT_ORIGIN, model_id);
      if ("error" in located) {
        return {
          content: [{ type: "text", text: located.error }],
          isError: true,
        };
      }
      if (env.DATA_SPLIT_ENABLED === "true") {
        const origin = `${env.RANK_API_ORIGIN.replace(/\/$/, "")}/v1/vocabulary`;
        const envelope = await fetchDisplayVocabulary();
        if (envelope.status < 400 && isRecord(envelope.body) && isRecord(envelope.body.models)) {
          envelope.body = envelope.body.models[model_id] ?? null;
        }
        return asToolResult(envelope);
      }
      return asToolResult(await fetchOrigin(located.origin));
    },
  );

  server.registerTool(
    "list_use_cases",
    {
      description: agentCopy.tools.list_use_cases,
      inputSchema: z.object({}),
    },
    async () => {
      const origin = `${env.EXPORT_ORIGIN.replace(/\/$/, "")}/api/rank/profiles.json`;
      return asToolResult(await fetchOrigin(origin));
    },
  );

  server.registerTool(
    "policy_check",
    {
      description: agentCopy.tools.policy_check,
      inputSchema: policyInput,
    },
    async (args) => {
      const origin = `${env.RANK_API_ORIGIN.replace(/\/$/, "")}/v1/policy-check`;
      return asToolResult(await fetchDecision(origin, args));
    },
  );

  server.registerTool(
    "decide",
    {
      description: agentCopy.tools.decide,
      inputSchema: decisionSpecInput,
    },
    async (spec) => {
      const origin = `${env.RANK_API_ORIGIN.replace(/\/$/, "")}/v1/decide`;
      const envelope = await fetchDecision(origin, spec);
      const result = asToolResult(envelope);
      if (result.isError) return result;
      return {
        ...result,
        content: [
          ...result.content,
          { type: "text" as const, text: decisionSummary(envelope.body) },
        ],
      };
    },
  );

  server.registerTool(
    "vocab",
    {
      description: agentCopy.tools.vocab,
      inputSchema: vocabInput,
    },
    async (args) => {
      const section = args.section ?? "starter";
      const split = env.DATA_SPLIT_ENABLED === "true";
      const query = new URLSearchParams({ section, detail: args.detail ?? "compact" });
      if (args.search !== undefined) query.set("search", args.search);
      if (args.id !== undefined) query.append("id", args.id);
      for (const id of args.ids ?? []) query.append("ids", id);
      if (args.offset !== undefined) query.set("offset", String(args.offset));
      if (args.limit !== undefined) query.set("limit", String(args.limit));
      const origin = `${env.EXPORT_ORIGIN.replace(/\/$/, "")}/api/decision/vocabulary.json`;
      const envelope = split ? await fetchDisplayVocabulary(`?${query}`) : await fetchOrigin(origin);
      if (envelope.status < 400 && isRecord(envelope.body)) {
        // Older Workers ignore lookup parameters and return the full vocabulary.
        // Keep agent responses compact while the two Workers roll out independently.
        envelope.body = split && !("vocabulary_version" in envelope.body)
          ? envelope.body[section]
          : lookupVocabulary(envelope.body, args);
      }
      return asToolResult(envelope);
    },
  );

  server.registerTool(
    "feedback",
    {
      description: agentCopy.tools.feedback,
      inputSchema: feedbackInput,
    },
    async (args) => {
      const origin = `${env.RANK_API_ORIGIN.replace(/\/$/, "")}/v1/feedback`;
      const headers = new Headers({ "content-type": "application/json" });
      // The rank Worker limits feedback per caller. Through the service binding
      // it sees no caller address of its own, so this one is forwarded. It is
      // an HMAC input there and is never stored.
      const address = incomingClientAddress(mcpCtx.requestInfo);
      if (address) headers.set("x-modelspec-client-ip", address);
      return asToolResult(
        await fetchOrigin(
          origin,
          { method: "POST", headers, body: jsonBody({ ...args, client: "mcp" }) },
          env.RANK,
        ),
      );
    },
  );

  return server;
}

export function handlerOptions() {
  return {
    route: "/mcp",
    allowedHostnames: ["api.modelspec.dev", "localhost", "127.0.0.1"],
    allowedOriginHostnames: ["localhost", "127.0.0.1"],
  };
}

export function mcpHandler(env: Env) {
  return createMcpHandler(
    (ctx) => createModelspecServer(env, ctx),
    handlerOptions(),
  );
}
